import { describe, expect, it } from 'vitest';
import { layoutERD } from './erd';
import type { DBStudioTableDetails } from '$types';

const tables: DBStudioTableDetails[] = [
	{
		schema: 'public',
		name: 'users',
		columns: [{ name: 'id', dataType: 'uuid', nullable: false, primaryKey: true, autoGenerated: false }],
		foreignKeys: [],
		indexes: [],
		constraints: []
	},
	{
		schema: 'public',
		name: 'posts',
		columns: [
			{ name: 'id', dataType: 'uuid', nullable: false, primaryKey: true, autoGenerated: false },
			{ name: 'user_id', dataType: 'uuid', nullable: false, primaryKey: false, autoGenerated: false }
		],
		foreignKeys: [{ name: 'posts_user_id_fkey', column: 'user_id', referencedSchema: 'public', referencedTable: 'users', referencedColumn: 'id', onUpdate: 'NO ACTION', onDelete: 'CASCADE' }],
		indexes: [],
		constraints: []
	}
];

describe('layoutERD', () => {
	it('connects foreign keys to matching table nodes', () => {
		const graph = layoutERD(tables);
		expect(graph.nodes).toHaveLength(2);
		expect(graph.edges).toHaveLength(1);
		expect(graph.edges[0].from.id).toBe('public.posts');
		expect(graph.edges[0].to.id).toBe('public.users');
	});

	it('places a dependent table after its referenced table in LR layout', () => {
		const graph = layoutERD(tables, { direction: 'LR' });
		const users = graph.nodes.find((node) => node.id === 'public.users');
		const posts = graph.nodes.find((node) => node.id === 'public.posts');
		expect(users).toBeDefined();
		expect(posts).toBeDefined();
		expect(posts!.x).toBeGreaterThan(users!.x);
	});

	it('places a dependent table below its referenced table in TB layout', () => {
		const graph = layoutERD(tables, { direction: 'TB' });
		const users = graph.nodes.find((node) => node.id === 'public.users');
		const posts = graph.nodes.find((node) => node.id === 'public.posts');
		expect(posts!.y).toBeGreaterThan(users!.y);
	});

	it('keeps disconnected tables in separate visual groups', () => {
		const copy = structuredClone(tables);
		copy.push({ schema: 'public', name: 'settings', columns: [], foreignKeys: [], indexes: [], constraints: [] });
		const graph = layoutERD(copy);
		expect(graph.groups).toBe(2);
		expect(graph.nodes.find((node) => node.id === 'public.settings')?.group).not.toBe(graph.nodes.find((node) => node.id === 'public.users')?.group);
	});

	it('ignores references outside the loaded schema graph', () => {
		const copy = structuredClone(tables);
		copy[1].foreignKeys[0].referencedSchema = 'external';
		expect(layoutERD(copy).edges).toHaveLength(0);
	});
});
