import { describe, expect, it } from 'vitest';
import { layoutERD } from './erd';
import type { DBStudioTableDetails } from '$types';

const tables: DBStudioTableDetails[] = [
	{
		schema: 'public',
		name: 'users',
		columns: [{ name: 'id', dataType: 'uuid', nullable: false, primaryKey: true, autoGenerated: false }],
		foreignKeys: [],
		indexes: [],
		constraints: []
	},
	{
		schema: 'public',
		name: 'posts',
		columns: [
			{ name: 'id', dataType: 'uuid', nullable: false, primaryKey: true, autoGenerated: false },
			{ name: 'user_id', dataType: 'uuid', nullable: false, primaryKey: false, autoGenerated: false }
		],
		foreignKeys: [{ name: 'posts_user_id_fkey', column: 'user_id', referencedSchema: 'public', referencedTable: 'users', referencedColumn: 'id', onUpdate: 'NO ACTION', onDelete: 'CASCADE' }],
		indexes: [],
		constraints: []
	}
];

describe('layoutERD', () => {
	it('connects foreign keys to matching table nodes', () => {
		const graph = layoutERD(tables, 2);
		expect(graph.nodes).toHaveLength(2);
		expect(graph.edges).toHaveLength(1);
		expect(graph.edges[0].from.id).toBe('public.posts');
		expect(graph.edges[0].to.id).toBe('public.users');
	});

	it('ignores references outside the loaded schema graph', () => {
		const copy = structuredClone(tables);
		copy[1].foreignKeys[0].referencedSchema = 'external';
		expect(layoutERD(copy).edges).toHaveLength(0);
	});
});
