import { describe, expect, it } from 'vitest';
import type { DBStudioColumn } from '$types';
import {
	activeDatabaseNowColumns,
	buildTouchedValues,
	columnDefaultValue,
	columnHasDefault,
	isTemporalColumn,
	missingRequiredInsertColumns
} from './mutation';

const base = (overrides: Partial<DBStudioColumn> & Record<string, unknown> = {}): DBStudioColumn => ({
	name: 'value',
	dataType: 'text',
	nullable: false,
	primaryKey: false,
	autoGenerated: false,
	...overrides
} as DBStudioColumn);

describe('DB Studio mutation helpers', () => {
	it('reads optional database default metadata without changing the legacy type contract', () => {
		const column = base({ hasDefault: true, defaultValue: 'CURRENT_TIMESTAMP' });
		expect(columnHasDefault(column)).toBe(true);
		expect(columnDefaultValue(column)).toBe('CURRENT_TIMESTAMP');
	});

	it('recognizes common temporal column declarations', () => {
		expect(isTemporalColumn(base({ dataType: 'timestamp with time zone' }))).toBe(true);
		expect(isTemporalColumn(base({ dataType: 'datetime(6)' }))).toBe(true);
		expect(isTemporalColumn(base({ dataType: 'date' }))).toBe(true);
		expect(isTemporalColumn(base({ dataType: 'varchar(255)' }))).toBe(false);
	});

	it('sends only fields the user actually touched', () => {
		expect(buildTouchedValues({ name: 'demo', created_at: '' }, { name: true })).toEqual({ name: 'demo' });
	});

	it('allows required insert columns to be satisfied by defaults or database time', () => {
		const columns = [
			base({ name: 'name' }),
			base({ name: 'created_at', dataType: 'timestamp', hasDefault: true }),
			base({ name: 'updated_at', dataType: 'timestamp' })
		];
		expect(missingRequiredInsertColumns(columns, { name: true }, { updated_at: true }).map((column) => column.name)).toEqual([]);
		expect(missingRequiredInsertColumns(columns, { name: true }, {}).map((column) => column.name)).toEqual(['updated_at']);
	});

	it('sorts active database-time fields deterministically', () => {
		expect(activeDatabaseNowColumns({ updated_at: true, created_at: true, ignored: false })).toEqual(['created_at', 'updated_at']);
	});
});
