import type { DBStudioColumn } from '$types';

export type MutationValueKind =
	| 'unsupported'
	| 'text'
	| 'integer'
	| 'decimal'
	| 'float'
	| 'boolean'
	| 'uuid'
	| 'enum'
	| 'temporal';

export function isTemporalColumn(column: DBStudioColumn): boolean {
	const kind = column.dataType.trim().toLowerCase();
	return kind.includes('timestamp') || kind.includes('datetime') || kind === 'date' || kind.startsWith('date(') || kind.includes('time');
}

export function mutationValueKind(column: DBStudioColumn): MutationValueKind {
	if ((column.enumValues?.length ?? 0) > 0) return 'enum';
	if (isTemporalColumn(column)) return 'temporal';

	const kind = column.dataType.trim().toLowerCase();
	if (
		kind.includes('json') ||
		kind.includes('blob') ||
		kind.includes('binary') ||
		kind.includes('bytea') ||
		kind.includes('geometry') ||
		kind.includes('geography') ||
		kind.includes('xml') ||
		kind.includes('array') ||
		kind.includes('range')
	) return 'unsupported';
	if (kind === 'boolean' || kind === 'bool' || kind.startsWith('tinyint(1)')) return 'boolean';
	if (kind.includes('uuid')) return 'uuid';
	if (kind.includes('int')) return 'integer';
	if (kind.includes('numeric') || kind.includes('decimal')) return 'decimal';
	if (kind.includes('real') || kind.includes('double') || kind.includes('float')) return 'float';
	if (kind.includes('char') || kind.includes('text') || kind.includes('clob')) return 'text';
	return 'unsupported';
}

export function isEditableMutationColumn(column: DBStudioColumn): boolean {
	return !column.autoGenerated && !column.primaryKey && mutationValueKind(column) !== 'unsupported';
}

export function isNumericMutationColumn(column: DBStudioColumn): boolean {
	const kind = mutationValueKind(column);
	return kind === 'integer' || kind === 'decimal' || kind === 'float';
}

export function buildTouchedValues(
	draftValues: Record<string, string>,
	touched: Record<string, boolean>,
	nullValues: Record<string, boolean>
): Record<string, string | null> {
	return Object.fromEntries(
		Object.keys(touched)
			.filter((name) => touched[name])
			.sort()
			.map((name) => [name, nullValues[name] ? null : (draftValues[name] ?? '')])
	);
}

export function activeDatabaseNowColumns(databaseNow: Record<string, boolean>): string[] {
	return Object.keys(databaseNow).filter((name) => databaseNow[name]).sort();
}
