import { describe, expect, it } from 'vitest';
import type { DBStudioColumn } from '$types';
import {
	activeDatabaseNowColumns,
	buildTouchedValues,
	isEditableMutationColumn,
	isNumericMutationColumn,
	isTemporalColumn,
	mutationValueKind
} from './mutation';

const base = (overrides: Partial<DBStudioColumn> = {}): DBStudioColumn => ({
	name: 'value',
	dataType: 'text',
	nullable: false,
	primaryKey: false,
	autoGenerated: false,
	...overrides
});

describe('DB Studio mutation helpers', () => {
	it('recognizes common temporal column declarations', () => {
		expect(isTemporalColumn(base({ dataType: 'timestamp with time zone' }))).toBe(true);
		expect(isTemporalColumn(base({ dataType: 'datetime(6)' }))).toBe(true);
		expect(isTemporalColumn(base({ dataType: 'date' }))).toBe(true);
		expect(isTemporalColumn(base({ dataType: 'varchar(255)' }))).toBe(false);
	});

	it('classifies the stable scalar write boundary', () => {
		expect(mutationValueKind(base({ dataType: 'text' }))).toBe('text');
		expect(mutationValueKind(base({ dataType: 'bigint' }))).toBe('integer');
		expect(mutationValueKind(base({ dataType: 'numeric(12,2)' }))).toBe('decimal');
		expect(mutationValueKind(base({ dataType: 'double precision' }))).toBe('float');
		expect(mutationValueKind(base({ dataType: 'boolean' }))).toBe('boolean');
		expect(mutationValueKind(base({ dataType: 'uuid' }))).toBe('uuid');
		expect(mutationValueKind(base({ dataType: 'USER-DEFINED', enumValues: ['draft', 'published'] }))).toBe('enum');
		expect(mutationValueKind(base({ dataType: 'jsonb' }))).toBe('unsupported');
		expect(mutationValueKind(base({ dataType: 'timestamp' }))).toBe('temporal');
	});

	it('keeps primary keys, generated columns, and complex types outside the editor', () => {
		expect(isEditableMutationColumn(base({ primaryKey: true }))).toBe(false);
		expect(isEditableMutationColumn(base({ autoGenerated: true }))).toBe(false);
		expect(isEditableMutationColumn(base({ dataType: 'jsonb' }))).toBe(false);
		expect(isEditableMutationColumn(base({ dataType: 'varchar(255)' }))).toBe(true);
		expect(isNumericMutationColumn(base({ dataType: 'integer' }))).toBe(true);
		expect(isNumericMutationColumn(base({ dataType: 'text' }))).toBe(false);
	});

	it('sends only touched fields and preserves explicit NULL', () => {
		expect(buildTouchedValues({ name: 'demo', notes: '' }, { name: true, notes: false })).toEqual({ name: 'demo' });
		expect(buildTouchedValues({ name: 'demo', notes: '' }, { name: false, notes: true }, { notes: true })).toEqual({ notes: null });
	});

	it('sorts active database-time fields deterministically', () => {
		expect(activeDatabaseNowColumns({ updated_at: true, created_at: true, ignored: false })).toEqual(['created_at', 'updated_at']);
	});
});
