import type { DBStudioColumn } from '$types';

type ColumnWithDefaults = DBStudioColumn & {
	hasDefault?: boolean;
	defaultValue?: string;
};

export function columnHasDefault(column: DBStudioColumn): boolean {
	return Boolean((column as ColumnWithDefaults).hasDefault);
}

export function columnDefaultValue(column: DBStudioColumn): string {
	return (column as ColumnWithDefaults).defaultValue?.trim() ?? '';
}

export function isTemporalColumn(column: DBStudioColumn): boolean {
	const kind = column.dataType.trim().toLowerCase();
	return kind.includes('timestamp') || kind.includes('datetime') || kind === 'date' || kind.startsWith('date(') || kind.includes('time');
}

export function buildTouchedValues(draftValues: Record<string, string>, touched: Record<string, boolean>): Record<string, string> {
	return Object.fromEntries(
		Object.keys(touched)
			.filter((name) => touched[name])
			.sort()
			.map((name) => [name, draftValues[name] ?? ''])
	);
}

export function missingRequiredInsertColumns(
	columns: DBStudioColumn[],
	touched: Record<string, boolean>,
	databaseNow: Record<string, boolean>
): DBStudioColumn[] {
	return columns.filter((column) =>
		!column.autoGenerated &&
		!column.nullable &&
		!columnHasDefault(column) &&
		!touched[column.name] &&
		!databaseNow[column.name]
	);
}

export function activeDatabaseNowColumns(databaseNow: Record<string, boolean>): string[] {
	return Object.keys(databaseNow).filter((name) => databaseNow[name]).sort();
}
