<script lang="ts">
	import { onMount } from 'svelte';
	import { page } from '$app/stores';
	import ActionButton from '$components/ActionButton.svelte';
	import EmptyState from '$components/EmptyState.svelte';
	import ErrorState from '$components/ErrorState.svelte';
	import IconButton from '$components/IconButton.svelte';
	import Pagination from '$components/Pagination.svelte';
	import SectionPanel from '$components/SectionPanel.svelte';
	import TableShell from '$components/TableShell.svelte';
	import { api } from '$api';
	import { toast } from '$stores/toast';
	import type { DBStudioColumn, DBStudioRowPage, DBStudioSchema, DBStudioStatus, DBStudioTable } from '$types';

	type MutationMode = 'insert' | 'edit' | 'delete';

	let status: DBStudioStatus | null = null;
	let schemas: DBStudioSchema[] = [];
	let tables: DBStudioTable[] = [];
	let rows: DBStudioRowPage | null = null;
	let selectedSchema = '';
	let selectedTable = '';
	let tableSearch = '';
	let rowSearch = '';
	let appliedRowSearch = '';
	let enumFilters: Record<string, string> = {};
	let appliedEnumFilters: Record<string, string> = {};
	let pageIndex = 0;
	let pageSize = 100;
	let loading = true;
	let loadingTables = false;
	let loadingRows = false;
	let error = '';
	let tableError = '';
	let rowsError = '';
	let startingWrite = false;
	let revokingWrite = false;
	let mutating = false;
	let mutationMode: MutationMode | null = null;
	let selectedRow: Record<string, unknown> | null = null;
	let draftValues: Record<string, string> = {};
	let now = Date.now();
	let lastPageIndex = 0;

	$: projectId = $page.params.id;
	$: connection = status?.connection ?? null;
	$: writeAccess = status?.writeAccess ?? null;
	$: writeExpiresAt = writeAccess ? new Date(writeAccess.expiresAt).getTime() : 0;
	$: writeActive = Boolean(writeAccess && writeExpiresAt > now);
	$: writeRemaining = writeActive ? formatDuration(writeExpiresAt - now) : '';
	$: columns = rows?.columns ?? [];
	$: primaryColumns = columns.filter((column) => column.primaryKey);
	$: enumColumns = columns.filter((column) => (column.enumValues?.length ?? 0) > 0);
	$: writableColumns = columns.filter((column) => !column.autoGenerated && !column.primaryKey);
	$: insertColumns = columns.filter((column) => !column.autoGenerated);
	$: filteredTables = tables.filter((table) => table.name.toLowerCase().includes(tableSearch.trim().toLowerCase()));
	$: selectedTableLabel = selectedSchema && selectedTable ? `${selectedSchema}.${selectedTable}` : 'No table selected';
	$: activeFilterCount = Number(Boolean(appliedRowSearch)) + Object.values(appliedEnumFilters).filter(Boolean).length;
	$: filterDirty = rowSearch.trim() !== appliedRowSearch || JSON.stringify(cleanEnumFilters(enumFilters)) !== JSON.stringify(appliedEnumFilters);
	$: if (pageIndex !== lastPageIndex) {
		lastPageIndex = pageIndex;
		void loadRows();
	}

	onMount(() => {
		void load();
		const timer = window.setInterval(() => {
			now = Date.now();
		}, 1000);
		return () => window.clearInterval(timer);
	});

	async function load() {
		loading = true;
		error = '';
		try {
			status = await api.dbStudio.status(projectId);
			if (!status.connected) return;
			schemas = await api.dbStudio.schemas(projectId);
			selectedSchema = selectedSchema || schemas[0]?.name || '';
			if (selectedSchema) {
				await loadTables();
			}
		} catch (err) {
			error = err instanceof Error ? err.message : 'Failed to load database studio';
		} finally {
			loading = false;
		}
	}

	async function loadTables() {
		if (!selectedSchema) return;
		loadingTables = true;
		tableError = '';
		try {
			tables = await api.dbStudio.tables(projectId, selectedSchema);
			const previousTable = selectedTable;
			selectedTable = tables.some((table) => table.name === selectedTable) ? selectedTable : tables[0]?.name || '';
			if (selectedTable !== previousTable) {
				resetRowFilters();
			}
			pageIndex = 0;
			if (selectedTable) {
				await loadRows();
			} else {
				rows = null;
			}
		} catch (err) {
			tableError = err instanceof Error ? err.message : 'Failed to load tables';
		} finally {
			loadingTables = false;
		}
	}

	async function loadRows() {
		if (!selectedSchema || !selectedTable) return;
		loadingRows = true;
		rowsError = '';
		try {
			rows = await api.dbStudio.rows(projectId, selectedSchema, selectedTable, pageSize, pageIndex * pageSize, {
				search: appliedRowSearch,
				enumFilters: appliedEnumFilters
			});
		} catch (err) {
			rowsError = err instanceof Error ? err.message : 'Failed to load rows';
		} finally {
			loadingRows = false;
		}
	}

	async function handleSchemaChange(event: Event) {
		selectedSchema = (event.currentTarget as HTMLSelectElement).value;
		selectedTable = '';
		await loadTables();
	}

	async function chooseTable(table: DBStudioTable) {
		if (selectedTable === table.name && selectedSchema === table.schema) return;
		selectedSchema = table.schema;
		selectedTable = table.name;
		pageIndex = 0;
		resetRowFilters();
		await loadRows();
	}

	async function applyRowFilters() {
		appliedRowSearch = rowSearch.trim();
		appliedEnumFilters = cleanEnumFilters(enumFilters);
		pageIndex = 0;
		if (lastPageIndex === 0) {
			await loadRows();
		}
	}

	async function clearRowFilters() {
		rowSearch = '';
		enumFilters = {};
		appliedRowSearch = '';
		appliedEnumFilters = {};
		pageIndex = 0;
		if (lastPageIndex === 0) {
			await loadRows();
		}
	}

	function resetRowFilters() {
		rowSearch = '';
		appliedRowSearch = '';
		enumFilters = {};
		appliedEnumFilters = {};
	}

	function cleanEnumFilters(filters: Record<string, string>) {
		return Object.fromEntries(Object.entries(filters).filter(([, value]) => Boolean(value)));
	}

	async function startWriteMode() {
		startingWrite = true;
		try {
			const session = await api.dbStudio.startWriteSession(projectId, 15);
			status = status ? { ...status, writeAccess: session } : await api.dbStudio.status(projectId);
			toast.success('Write mode enabled for 15 minutes');
		} catch (err) {
			toast.error(err instanceof Error ? err.message : 'Failed to enable write mode');
		} finally {
			startingWrite = false;
		}
	}

	async function revokeWriteMode() {
		if (!writeAccess) return;
		revokingWrite = true;
		try {
			await api.dbStudio.revokeWriteSession(projectId, writeAccess.id);
			if (status) status = { ...status, writeAccess: null };
			toast.success('Write mode revoked');
		} catch (err) {
			toast.error(err instanceof Error ? err.message : 'Failed to revoke write mode');
		} finally {
			revokingWrite = false;
		}
	}

	function openInsert() {
		mutationMode = 'insert';
		selectedRow = null;
		draftValues = Object.fromEntries(insertColumns.map((column) => [column.name, '']));
	}

	function openEdit(row: Record<string, unknown>) {
		mutationMode = 'edit';
		selectedRow = row;
		draftValues = Object.fromEntries(writableColumns.map((column) => [column.name, valueToInput(row[column.name])]));
	}

	function openDelete(row: Record<string, unknown>) {
		mutationMode = 'delete';
		selectedRow = row;
		draftValues = {};
	}

	function closeMutation() {
		mutationMode = null;
		selectedRow = null;
		draftValues = {};
	}

	async function submitMutation() {
		if (!mutationMode || !selectedSchema || !selectedTable) return;
		mutating = true;
		const payload = {
			schema: selectedSchema,
			table: selectedTable,
			values: draftValues,
			primaryKey: selectedRow ? primaryKeyPayload(selectedRow) : {}
		};
		try {
			if (mutationMode === 'insert') await api.dbStudio.insert(projectId, payload);
			if (mutationMode === 'edit') await api.dbStudio.update(projectId, payload);
			if (mutationMode === 'delete') await api.dbStudio.delete(projectId, payload);
			toast.success('Database row saved');
			closeMutation();
			await loadRows();
		} catch (err) {
			toast.error(err instanceof Error ? err.message : 'Failed to save database row');
		} finally {
			mutating = false;
		}
	}

	function primaryKeyPayload(row: Record<string, unknown>) {
		return Object.fromEntries(primaryColumns.map((column) => [column.name, row[column.name]]));
	}

	function valueToInput(value: unknown) {
		if (value === null || value === undefined) return '';
		if (typeof value === 'object') return JSON.stringify(value);
		return String(value);
	}

	function formatCell(value: unknown) {
		if (value === null || value === undefined) return 'NULL';
		if (typeof value === 'object') return JSON.stringify(value);
		return String(value);
	}

	function formatDuration(ms: number) {
		const total = Math.max(0, Math.floor(ms / 1000));
		const minutes = Math.floor(total / 60);
		const seconds = total % 60;
		return `${minutes}m ${seconds.toString().padStart(2, '0')}s`;
	}

	function driverLabel(value: string) {
		if (value === 'postgres') return 'PostgreSQL';
		if (value === 'mariadb') return 'MariaDB';
		return 'MySQL';
	}
</script>

{#if loading}
	<SectionPanel title="Database Studio" description="Loading database connection and schema metadata.">
		<div class="space-y-3">
			<div class="h-16 animate-pulse rounded-md bg-gray-100 dark:bg-gray-800"></div>
			<div class="h-48 animate-pulse rounded-md bg-gray-100 dark:bg-gray-800"></div>
		</div>
	</SectionPanel>
{:else if error}
	<div class="surface overflow-hidden">
		<ErrorState title="Could not load Database Studio" message={error} on:retry={() => void load()} />
	</div>
{:else if !status?.configured}
	<SectionPanel title="Database Studio" description="No supported database connection was detected from this project's environment variables.">
		<EmptyState title="No database connection found." description="Add DATABASE_URL or DB_HOST, DB_PORT, DB_NAME, DB_USER, and DB_PASSWORD in Environment, then redeploy or refresh this page." />
	</SectionPanel>
{:else}
	<div class="space-y-5">
		<SectionPanel title="Database Studio" description="Browse and lightly edit project database rows without opening a full SQL client.">
			<svelte:fragment slot="actions">
				<ActionButton variant="secondary" on:click={() => void load()} disabled={loadingRows || loadingTables}>Refresh</ActionButton>
				{#if writeActive}
					<ActionButton variant="ghostDanger" on:click={revokeWriteMode} loading={revokingWrite} loadingLabel="Revoking...">Disable write</ActionButton>
				{:else}
					<ActionButton variant="primary" on:click={startWriteMode} loading={startingWrite} loadingLabel="Enabling...">Enable write</ActionButton>
				{/if}
			</svelte:fragment>

			<div class="grid gap-3 text-sm md:grid-cols-4">
				<div>
					<p class="text-xs text-gray-500 dark:text-gray-400">Status</p>
					<p class="mt-1 font-medium {status.connected ? 'text-brand-700 dark:text-brand-300' : 'text-red-600 dark:text-red-300'}">
						{status.connected ? 'Connected' : 'Unavailable'}
					</p>
				</div>
				<div>
					<p class="text-xs text-gray-500 dark:text-gray-400">Driver</p>
					<p class="mt-1 font-mono text-gray-950 dark:text-white">{connection ? driverLabel(connection.driver) : '-'}</p>
				</div>
				<div>
					<p class="text-xs text-gray-500 dark:text-gray-400">Database</p>
					<p class="mt-1 truncate font-mono text-gray-950 dark:text-white">{connection?.database ?? '-'}</p>
				</div>
				<div>
					<p class="text-xs text-gray-500 dark:text-gray-400">Write mode</p>
					<p class="mt-1 font-medium {writeActive ? 'text-yellow-700 dark:text-yellow-200' : 'text-gray-600 dark:text-gray-300'}">
						{writeActive ? `Active ${writeRemaining}` : 'Read-only'}
					</p>
				</div>
			</div>
			{#if !status.connected}
				<p class="mt-4 rounded-md border border-red-200 bg-red-50 px-3 py-2 text-sm text-red-700 dark:border-red-900/60 dark:bg-red-950/20 dark:text-red-200">
					{status.message}
				</p>
			{/if}
		</SectionPanel>

		{#if status.connected}
			<div class="grid gap-5 lg:grid-cols-[18rem_minmax(0,1fr)]">
				<SectionPanel title="Tables" description="Choose one table at a time." contentClass="p-0">
					<div class="border-b border-gray-100 p-3 dark:border-gray-800">
						<label class="mb-1 block text-xs font-medium text-gray-600 dark:text-gray-300" for="schema">Schema</label>
						<select id="schema" value={selectedSchema} on:change={handleSchemaChange} class="field w-full">
							{#each schemas as schema}
								<option value={schema.name}>{schema.name}</option>
							{/each}
						</select>
						<input value={tableSearch} placeholder="Search tables" class="field mt-3 w-full" on:input={(event) => (tableSearch = (event.currentTarget as HTMLInputElement).value)} />
					</div>
					{#if tableError}
						<ErrorState message={tableError} on:retry={() => void loadTables()} />
					{:else if loadingTables}
						<div class="space-y-2 p-3">
							{#each [1, 2, 3, 4] as _}
								<div class="h-9 animate-pulse rounded-md bg-gray-100 dark:bg-gray-800"></div>
							{/each}
						</div>
					{:else if filteredTables.length === 0}
						<EmptyState title="No tables found." compact />
					{:else}
						<div class="max-h-[34rem] overflow-auto p-2">
							{#each filteredTables as table}
								<button
									type="button"
									class="mb-1 flex w-full items-center justify-between gap-2 rounded-md px-3 py-2 text-left text-sm transition-colors {selectedSchema === table.schema && selectedTable === table.name
										? 'bg-brand-50 text-brand-900 dark:bg-brand-500/10 dark:text-brand-100'
										: 'text-gray-600 hover:bg-gray-50 hover:text-gray-950 dark:text-gray-300 dark:hover:bg-gray-900 dark:hover:text-white'}"
									on:click={() => void chooseTable(table)}
								>
									<span class="truncate font-mono">{table.name}</span>
								</button>
							{/each}
						</div>
					{/if}
				</SectionPanel>

				<TableShell
					title={selectedTableLabel}
					description={activeFilterCount > 0
						? `${activeFilterCount} active filter${activeFilterCount === 1 ? '' : 's'} · ${primaryColumns.length > 0 ? `Primary key: ${primaryColumns.map((column) => column.name).join(', ')}` : 'No primary key'}`
						: primaryColumns.length > 0
							? `Primary key: ${primaryColumns.map((column) => column.name).join(', ')}`
							: 'Edit/delete disabled because this table has no primary key.'}
					loading={loadingRows}
					error={rowsError}
					empty={false}
					loadingRows={5}
					on:retry={() => void loadRows()}
				>
					<svelte:fragment slot="actions">
						<ActionButton variant="secondary" size="xs" on:click={() => void loadRows()} disabled={!selectedTable || loadingRows}>Refresh rows</ActionButton>
						{#if activeFilterCount > 0}
							<ActionButton variant="ghost" size="xs" on:click={() => void clearRowFilters()} disabled={loadingRows}>Clear filters</ActionButton>
						{/if}
						<ActionButton variant="primary" size="xs" on:click={openInsert} disabled={!writeActive || columns.length === 0}>Insert row</ActionButton>
					</svelte:fragment>

					<div class="border-b border-gray-100 bg-gray-50/70 p-3 dark:border-gray-800 dark:bg-gray-950/60">
						<div class="grid gap-3 lg:grid-cols-[minmax(14rem,1fr)_auto] lg:items-end">
							<label class="block">
								<span class="mb-1 block text-xs font-medium text-gray-600 dark:text-gray-300">Search rows</span>
								<input
									value={rowSearch}
									class="field w-full"
									placeholder="Search scalar columns"
									on:input={(event) => (rowSearch = (event.currentTarget as HTMLInputElement).value)}
									on:keydown={(event) => {
										if (event.key === 'Enter') {
											event.preventDefault();
											void applyRowFilters();
										}
									}}
								/>
							</label>
							<div class="flex flex-wrap gap-2">
								<ActionButton variant={filterDirty ? 'primary' : 'secondary'} size="xs" on:click={() => void applyRowFilters()} disabled={loadingRows || !filterDirty}>Apply filters</ActionButton>
								<ActionButton
									variant="ghost"
									size="xs"
									on:click={() => void clearRowFilters()}
									disabled={loadingRows || (!rowSearch && activeFilterCount === 0 && Object.values(enumFilters).filter(Boolean).length === 0)}
								>
									Reset
								</ActionButton>
							</div>
						</div>
						{#if enumColumns.length > 0}
							<div class="mt-3 grid gap-3 sm:grid-cols-2 xl:grid-cols-4">
								{#each enumColumns as column}
									<label class="block">
										<span class="mb-1 block truncate text-xs font-medium text-gray-600 dark:text-gray-300" title={column.name}>
											{column.name}
										</span>
										<select
											class="field w-full"
											value={enumFilters[column.name] ?? ''}
											on:change={(event) => (enumFilters = { ...enumFilters, [column.name]: (event.currentTarget as HTMLSelectElement).value })}
										>
											<option value="">Any value</option>
											{#each column.enumValues ?? [] as value}
												<option {value}>{value}</option>
											{/each}
										</select>
									</label>
								{/each}
							</div>
						{/if}
						<p class="mt-2 text-xs text-gray-500 dark:text-gray-400">Search and enum filters are applied in SQL with pagination; MyPaas does not load the whole table into memory.</p>
					</div>

					{#if !rows || rows.rows.length === 0}
						<EmptyState
							title={activeFilterCount > 0 ? 'No rows match these filters.' : 'No rows in this table.'}
							description={activeFilterCount > 0 ? 'Adjust the search or enum filters, then apply again.' : ''}
							compact
						/>
					{:else}
						<table class="min-w-full divide-y divide-gray-100 text-sm dark:divide-gray-800">
							<thead class="bg-gray-50 text-left text-xs font-medium text-gray-500 dark:bg-gray-950 dark:text-gray-400">
								<tr>
									{#each columns as column}
										<th class="px-3 py-2 font-medium">
											<span class="inline-flex items-center gap-1">
												{column.name}
												{#if column.primaryKey}
													<span class="rounded bg-yellow-100 px-1.5 py-0.5 text-[10px] text-yellow-800 dark:bg-yellow-500/10 dark:text-yellow-200">PK</span>
												{/if}
												{#if (column.enumValues?.length ?? 0) > 0}
													<span class="rounded bg-brand-50 px-1.5 py-0.5 text-[10px] text-brand-700 dark:bg-brand-500/10 dark:text-brand-200">ENUM</span>
												{/if}
											</span>
										</th>
									{/each}
									<th class="w-32 px-3 py-2 text-right font-medium">Actions</th>
								</tr>
							</thead>
							<tbody class="divide-y divide-gray-100 dark:divide-gray-800">
								{#each rows?.rows ?? [] as row, rowIndex}
									<tr class="hover:bg-gray-50/70 dark:hover:bg-gray-900/60">
										{#each columns as column}
											<td class="max-w-72 truncate px-3 py-2 font-mono text-xs text-gray-700 dark:text-gray-200" title={formatCell(row[column.name])}>
												{formatCell(row[column.name])}
											</td>
										{/each}
										<td class="px-3 py-2">
											<div class="flex justify-end gap-1">
												<IconButton
													label={`Edit database row ${pageIndex * pageSize + rowIndex + 1}`}
													variant="ghost"
													on:click={() => openEdit(row)}
													disabled={!writeActive || primaryColumns.length === 0}
												>
													<svg class="h-4 w-4" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2" aria-hidden="true">
														<path stroke-linecap="round" stroke-linejoin="round" d="M16.862 3.487a2.121 2.121 0 013 3L8.25 18.1 4 19.5l1.4-4.25L16.862 3.487zM14.75 5.6l3 3" />
													</svg>
												</IconButton>
												<IconButton
													label={`Delete database row ${pageIndex * pageSize + rowIndex + 1}`}
													variant="danger"
													on:click={() => openDelete(row)}
													disabled={!writeActive || primaryColumns.length === 0}
												>
													<svg class="h-4 w-4" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2" aria-hidden="true">
														<path
															stroke-linecap="round"
															stroke-linejoin="round"
															d="M19 7l-.867 12.142A2 2 0 0116.138 21H7.862a2 2 0 01-1.995-1.858L5 7m5 4v6m4-6v6m1-10V4a1 1 0 00-1-1h-4a1 1 0 00-1 1v3M4 7h16"
														/>
													</svg>
												</IconButton>
											</div>
										</td>
									</tr>
								{/each}
							</tbody>
						</table>
					{/if}

					<svelte:fragment slot="footer">
						<Pagination bind:page={pageIndex} {pageSize} totalShown={rows?.rows.length ?? 0} hasNext={rows?.hasMore ?? false} loading={loadingRows} label="Rows" />
					</svelte:fragment>
				</TableShell>
			</div>
		{/if}
	</div>
{/if}

{#if mutationMode}
	<div class="fixed inset-0 z-50 flex items-center justify-center bg-gray-950/50 p-4">
		<div class="w-full max-w-2xl overflow-hidden rounded-md border border-gray-200 bg-white shadow-xl dark:border-gray-800 dark:bg-gray-950">
			<div class="border-b border-gray-100 px-5 py-4 dark:border-gray-800">
				<h2 class="text-sm font-semibold text-gray-950 dark:text-white">
					{mutationMode === 'insert' ? 'Insert row' : mutationMode === 'edit' ? 'Edit row' : 'Delete row'}
				</h2>
				<p class="mt-1 text-xs text-gray-500 dark:text-gray-400">{selectedTableLabel}</p>
			</div>
			<div class="max-h-[70vh] overflow-auto p-5">
				{#if mutationMode === 'delete'}
					<p class="text-sm leading-6 text-gray-600 dark:text-gray-300">Delete this row by primary key. This action runs immediately and cannot be undone by MyPaas.</p>
					<div class="mt-4 rounded-md border border-gray-200 bg-gray-50 p-3 text-xs dark:border-gray-800 dark:bg-gray-900">
						{#each primaryColumns as column}
							<p><span class="font-mono font-medium">{column.name}</span>: {formatCell(selectedRow?.[column.name])}</p>
						{/each}
					</div>
				{:else}
					<div class="grid gap-4 sm:grid-cols-2">
						{#each mutationMode === 'insert' ? insertColumns : writableColumns as column}
							<label class="block">
								<span class="mb-1 block text-xs font-medium text-gray-600 dark:text-gray-300">
									{column.name}
									<span class="font-normal text-gray-400">({column.dataType})</span>
								</span>
								<input
									value={draftValues[column.name] ?? ''}
									class="field w-full font-mono"
									placeholder={column.nullable ? 'nullable' : ''}
									on:input={(event) => (draftValues = { ...draftValues, [column.name]: (event.currentTarget as HTMLInputElement).value })}
								/>
							</label>
						{/each}
					</div>
				{/if}
			</div>
			<div class="flex justify-end gap-2 border-t border-gray-100 px-5 py-4 dark:border-gray-800">
				<ActionButton variant="ghost" on:click={closeMutation} disabled={mutating}>Cancel</ActionButton>
				<ActionButton variant={mutationMode === 'delete' ? 'danger' : 'primary'} on:click={() => void submitMutation()} loading={mutating} loadingLabel="Saving...">
					{mutationMode === 'delete' ? 'Delete row' : 'Save row'}
				</ActionButton>
			</div>
		</div>
	</div>
{/if}
