<script lang="ts">
	import { Clock3, Filter, Lock, Pencil, Plus, RefreshCw, RotateCcw, Save, Trash2, Unlock, X } from '@lucide/svelte';
	import { onMount } from 'svelte';
	import { page } from '$app/stores';
	import ActionButton from '$components/ActionButton.svelte';
	import EmptyState from '$components/EmptyState.svelte';
	import ErrorState from '$components/ErrorState.svelte';
	import IconButton from '$components/IconButton.svelte';
	import Pagination from '$components/Pagination.svelte';
	import SectionPanel from '$components/SectionPanel.svelte';
	import TableShell from '$components/TableShell.svelte';
	import { api } from '$api';
	import { toast } from '$stores/toast';
	import {
		activeDatabaseNowColumns,
		buildTouchedValues,
		columnDefaultValue,
		columnHasDefault,
		isTemporalColumn,
		missingRequiredInsertColumns
	} from '$lib/dbstudio/mutation';
	import type { DBStudioColumn, DBStudioRowPage, DBStudioSchema, DBStudioStatus, DBStudioTable } from '$types';

	type MutationMode = 'insert' | 'edit' | 'delete';

	const studioPageSize = 12;

	let status: DBStudioStatus | null = null;
	let schemas: DBStudioSchema[] = [];
	let tables: DBStudioTable[] = [];
	let rows: DBStudioRowPage | null = null;
	let selectedSchema = '';
	let selectedTable = '';
	let tableSearch = '';
	let rowSearch = '';
	let appliedRowSearch = '';
	let enumFilters: Record<string, string> = {};
	let appliedEnumFilters: Record<string, string> = {};
	let tablePageIndex = 0;
	let pageIndex = 0;
	let pageSize = studioPageSize;
	let loadingTables = false;
	let loadingRows = false;
	let error = '';
	let tableError = '';
	let rowsError = '';
	let startingWrite = false;
	let revokingWrite = false;
	let mutating = false;
	let mutationMode: MutationMode | null = null;
	let selectedRow: Record<string, unknown> | null = null;
	let draftValues: Record<string, string> = {};
	let touchedValues: Record<string, boolean> = {};
	let databaseNowValues: Record<string, boolean> = {};
	let now = Date.now();
	let lastPageIndex = 0;

	$: projectId = $page.params.id ?? '';
	$: connection = status?.connection ?? null;
	$: writeAccess = status?.writeAccess ?? null;
	$: writeExpiresAt = writeAccess ? new Date(writeAccess.expiresAt).getTime() : 0;
	$: writeActive = Boolean(writeAccess && writeExpiresAt > now);
	$: writeRemaining = writeActive ? formatDuration(writeExpiresAt - now) : '';
	$: columns = rows?.columns ?? [];
	$: primaryColumns = columns.filter((column) => column.primaryKey);
	$: enumColumns = columns.filter((column) => (column.enumValues?.length ?? 0) > 0);
	$: writableColumns = columns.filter((column) => !column.autoGenerated && !column.primaryKey);
	$: insertColumns = columns.filter((column) => !column.autoGenerated);
	$: filteredTables = tables.filter((table) => table.name.toLowerCase().includes(tableSearch.trim().toLowerCase()));
	$: tablePageCount = Math.max(1, Math.ceil(filteredTables.length / studioPageSize));
	$: if (tablePageIndex >= tablePageCount) tablePageIndex = Math.max(0, tablePageCount - 1);
	$: pagedTables = filteredTables.slice(tablePageIndex * studioPageSize, (tablePageIndex + 1) * studioPageSize);
	$: tableHasNext = (tablePageIndex + 1) * studioPageSize < filteredTables.length;
	$: selectedTableLabel = selectedSchema && selectedTable ? `${selectedSchema}.${selectedTable}` : 'No table selected';
	$: activeFilterCount = Number(Boolean(appliedRowSearch)) + Object.values(appliedEnumFilters).filter(Boolean).length;
	$: filterDirty = rowSearch.trim() !== appliedRowSearch || JSON.stringify(cleanEnumFilters(enumFilters)) !== JSON.stringify(appliedEnumFilters);
	$: missingRequiredColumns = mutationMode === 'insert' ? missingRequiredInsertColumns(insertColumns, touchedValues, databaseNowValues) : [];
	$: mutationHasChanges = Object.values(touchedValues).some(Boolean) || Object.values(databaseNowValues).some(Boolean);
	$: canSaveMutation = mutationMode === 'delete' || (mutationMode === 'insert' ? missingRequiredColumns.length === 0 : mutationHasChanges);
	$: if (pageIndex !== lastPageIndex) {
		lastPageIndex = pageIndex;
		void loadRows();
	}

	onMount(() => {
		void load();
		const timer = window.setInterval(() => {
			now = Date.now();
		}, 1000);
		return () => window.clearInterval(timer);
	});

	async function load() {
		error = '';
		try {
			status = await api.dbStudio.status(projectId);
			if (!status.connected) return;
			schemas = await api.dbStudio.schemas(projectId);
			selectedSchema = selectedSchema || schemas[0]?.name || '';
			if (selectedSchema) await loadTables();
		} catch (err) {
			error = err instanceof Error ? err.message : 'Failed to load database studio';
		}
	}

	async function loadTables() {
		if (!selectedSchema) return;
		loadingTables = true;
		tableError = '';
		try {
			tables = await api.dbStudio.tables(projectId, selectedSchema);
			const previousTable = selectedTable;
			selectedTable = tables.some((table) => table.name === selectedTable) ? selectedTable : tables[0]?.name || '';
			if (selectedTable !== previousTable) resetRowFilters();
			tablePageIndex = 0;
			pageIndex = 0;
			if (selectedTable) await loadRows();
			else rows = null;
		} catch (err) {
			tableError = err instanceof Error ? err.message : 'Failed to load tables';
		} finally {
			loadingTables = false;
		}
	}

	async function loadRows() {
		if (!selectedSchema || !selectedTable) return;
		loadingRows = true;
		rowsError = '';
		try {
			rows = await api.dbStudio.rows(projectId, selectedSchema, selectedTable, pageSize, pageIndex * pageSize, {
				search: appliedRowSearch,
				enumFilters: appliedEnumFilters
			});
		} catch (err) {
			rowsError = err instanceof Error ? err.message : 'Failed to load rows';
		} finally {
			loadingRows = false;
		}
	}

	async function handleSchemaChange(event: Event) {
		selectedSchema = (event.currentTarget as HTMLSelectElement).value;
		selectedTable = '';
		tablePageIndex = 0;
		await loadTables();
	}

	function handleTableSearch(event: Event) {
		tableSearch = (event.currentTarget as HTMLInputElement).value;
		tablePageIndex = 0;
	}

	async function chooseTable(table: DBStudioTable) {
		if (selectedTable === table.name && selectedSchema === table.schema) return;
		selectedSchema = table.schema;
		selectedTable = table.name;
		pageIndex = 0;
		resetRowFilters();
		await loadRows();
	}

	async function applyRowFilters() {
		appliedRowSearch = rowSearch.trim();
		appliedEnumFilters = cleanEnumFilters(enumFilters);
		pageIndex = 0;
		if (lastPageIndex === 0) await loadRows();
	}

	async function clearRowFilters() {
		rowSearch = '';
		enumFilters = {};
		appliedRowSearch = '';
		appliedEnumFilters = {};
		pageIndex = 0;
		if (lastPageIndex === 0) await loadRows();
	}

	function resetRowFilters() {
		rowSearch = '';
		appliedRowSearch = '';
		enumFilters = {};
		appliedEnumFilters = {};
	}

	function cleanEnumFilters(filters: Record<string, string>) {
		return Object.fromEntries(Object.entries(filters).filter(([, value]) => Boolean(value)));
	}

	async function startWriteMode() {
		startingWrite = true;
		try {
			const session = await api.dbStudio.startWriteSession(projectId, 15);
			status = status ? { ...status, writeAccess: session } : await api.dbStudio.status(projectId);
			toast.success('Write mode enabled for 15 minutes');
		} catch (err) {
			toast.error(err instanceof Error ? err.message : 'Failed to enable write mode');
		} finally {
			startingWrite = false;
		}
	}

	async function revokeWriteMode() {
		if (!writeAccess) return;
		revokingWrite = true;
		try {
			await api.dbStudio.revokeWriteSession(projectId, writeAccess.id);
			if (status) status = { ...status, writeAccess: null };
			toast.success('Write mode revoked');
		} catch (err) {
			toast.error(err instanceof Error ? err.message : 'Failed to revoke write mode');
		} finally {
			revokingWrite = false;
		}
	}

	function resetMutationDraft() {
		touchedValues = {};
		databaseNowValues = {};
	}

	function openInsert() {
		mutationMode = 'insert';
		selectedRow = null;
		draftValues = {};
		resetMutationDraft();
	}

	function openEdit(row: Record<string, unknown>) {
		mutationMode = 'edit';
		selectedRow = row;
		draftValues = Object.fromEntries(writableColumns.map((column) => [column.name, valueToInput(row[column.name])]));
		resetMutationDraft();
	}

	function openDelete(row: Record<string, unknown>) {
		mutationMode = 'delete';
		selectedRow = row;
		draftValues = {};
		resetMutationDraft();
	}

	function closeMutation() {
		mutationMode = null;
		selectedRow = null;
		draftValues = {};
		resetMutationDraft();
	}

	function setMutationValue(name: string, value: string) {
		draftValues = { ...draftValues, [name]: value };
		touchedValues = { ...touchedValues, [name]: true };
		databaseNowValues = { ...databaseNowValues, [name]: false };
	}

	function useDatabaseNow(name: string) {
		databaseNowValues = { ...databaseNowValues, [name]: true };
		touchedValues = { ...touchedValues, [name]: false };
	}

	function useDatabaseDefault(name: string) {
		databaseNowValues = { ...databaseNowValues, [name]: false };
		touchedValues = { ...touchedValues, [name]: false };
	}

	function defaultPlaceholder(column: DBStudioColumn) {
		const value = columnDefaultValue(column);
		return value ? `Database default · ${value}` : 'Database default';
	}

	async function submitMutation() {
		if (!mutationMode || !selectedSchema || !selectedTable) return;
		if (mutationMode === 'insert' && missingRequiredColumns.length > 0) {
			toast.error(`Required: ${missingRequiredColumns.map((column) => column.name).join(', ')}`);
			return;
		}
		if (mutationMode === 'edit' && !mutationHasChanges) return;
		mutating = true;
		const payload = {
			schema: selectedSchema,
			table: selectedTable,
			values: buildTouchedValues(draftValues, touchedValues),
			databaseNow: activeDatabaseNowColumns(databaseNowValues),
			primaryKey: selectedRow ? primaryKeyPayload(selectedRow) : {}
		};
		try {
			if (mutationMode === 'insert') await api.dbStudio.insert(projectId, payload);
			if (mutationMode === 'edit') await api.dbStudio.update(projectId, payload);
			if (mutationMode === 'delete') await api.dbStudio.delete(projectId, payload);
			toast.success(mutationMode === 'delete' ? 'Database row deleted' : 'Database row saved');
			closeMutation();
			await loadRows();
		} catch (err) {
			toast.error(err instanceof Error ? err.message : 'Failed to save database row');
		} finally {
			mutating = false;
		}
	}

	function primaryKeyPayload(row: Record<string, unknown>) {
		return Object.fromEntries(primaryColumns.map((column) => [column.name, row[column.name]]));
	}

	function valueToInput(value: unknown) {
		if (value === null || value === undefined) return '';
		if (typeof value === 'object') return JSON.stringify(value);
		return String(value);
	}

	function formatCell(value: unknown) {
		if (value === null || value === undefined) return 'NULL';
		if (typeof value === 'object') return JSON.stringify(value);
		return String(value);
	}

	function formatDuration(ms: number) {
		const total = Math.max(0, Math.floor(ms / 1000));
		const minutes = Math.floor(total / 60);
		const seconds = total % 60;
		return `${minutes}m ${seconds.toString().padStart(2, '0')}s`;
	}

	function driverLabel(value: string) {
		if (value === 'postgres') return 'PostgreSQL';
		if (value === 'mariadb') return 'MariaDB';
		if (value === 'sqlite') return 'SQLite';
		return 'MySQL';
	}
</script>

{#if error}
	<div class="workspace-section">
		<ErrorState title="Could not load Database Studio" message={error} on:retry={() => void load()} />
	</div>
{:else if status && !status.configured}
	<SectionPanel title="Connection" description="No supported database connection was detected from this project's environment variables.">
		<EmptyState title="No database connection found." description="Add DATABASE_URL, a SQLite path setting, or DB_HOST, DB_PORT, DB_NAME, DB_USER, and DB_PASSWORD in Environment, then redeploy or refresh this page." />
	</SectionPanel>
{:else if status}
	<div class="border-b border-[color:var(--workspace-divider)]" data-db-connection-strip>
		<div class="flex min-w-0 flex-wrap items-center gap-x-5 gap-y-2 px-4 py-2.5 lg:flex-nowrap">
			<div class="shrink-0 pr-1">
				<p class="text-sm font-semibold text-gray-950 dark:text-white">Connection</p>
			</div>
			<div class="inline-flex shrink-0 items-center gap-2">
				<span class="metric-label">Status</span>
				<span class="inline-flex items-center gap-1.5 text-sm font-medium text-gray-800 dark:text-gray-200"><span class="status-dot {status.connected ? 'bg-emerald-500' : 'bg-red-500'}"></span>{status.connected ? 'Connected' : 'Unavailable'}</span>
			</div>
			<div class="inline-flex shrink-0 items-center gap-2">
				<span class="metric-label">Driver</span>
				<span class="font-mono text-sm text-gray-950 dark:text-white">{connection ? driverLabel(connection.driver) : '—'}</span>
			</div>
			<div class="flex min-w-0 flex-1 items-center gap-2">
				<span class="metric-label shrink-0">Database</span>
				<span class="min-w-0 truncate font-mono text-sm text-gray-950 dark:text-white" title={connection?.database ?? ''}>{connection?.database ?? '—'}</span>
			</div>
			<div class="inline-flex shrink-0 items-center gap-2">
				<span class="metric-label">Write</span>
				<span class="inline-flex items-center gap-1.5 text-sm font-medium text-gray-700 dark:text-gray-300"><span class="status-dot {writeActive ? 'bg-amber-500' : 'bg-gray-400 dark:bg-gray-500'}"></span>{writeActive ? `Active · ${writeRemaining}` : 'Read-only'}</span>
			</div>
			<div class="ml-auto flex shrink-0 items-center gap-2">
				<ActionButton variant="secondary" size="sm" on:click={() => void load()} disabled={loadingRows || loadingTables}>
					<RefreshCw slot="icon" class="h-4 w-4" />
					Refresh
				</ActionButton>
				{#if writeActive}
					<ActionButton variant="ghostDanger" size="sm" on:click={revokeWriteMode} loading={revokingWrite} loadingLabel="Revoking">
						<Lock slot="icon" class="h-4 w-4" />
						Disable write
					</ActionButton>
				{:else}
					<ActionButton variant="primary" size="sm" on:click={startWriteMode} loading={startingWrite} loadingLabel="Enabling">
						<Unlock slot="icon" class="h-4 w-4" />
						Enable write
					</ActionButton>
				{/if}
			</div>
		</div>
		{#if !status.connected}<div class="border-t border-red-100 bg-red-50 px-4 py-2.5 text-sm text-red-700 dark:border-red-950 dark:bg-red-950/20 dark:text-red-300">{status.message}</div>{/if}
	</div>

	{#if status.connected}
		<div class="grid bg-gray-100/70 dark:bg-neutral-900 lg:grid-cols-[16rem_minmax(0,1fr)]">
			<div class="min-w-0 bg-white dark:bg-neutral-950 lg:border-r lg:border-gray-100/70 lg:dark:border-neutral-900">
				<SectionPanel title="Tables" description="Choose one table at a time." contentClass="p-0">
					<div class="border-b border-gray-100/70 p-3 dark:border-neutral-900">
						<label class="field-label" for="schema">Schema</label>
						<select id="schema" value={selectedSchema} on:change={handleSchemaChange} class="field w-full">
							{#each schemas as schema}<option value={schema.name}>{schema.name}</option>{/each}
						</select>
						<label class="field-label mt-3" for="table-search">Search tables</label>
						<input id="table-search" value={tableSearch} placeholder="Table name" class="field w-full" on:input={handleTableSearch} />
					</div>
					{#if tableError}
						<ErrorState message={tableError} on:retry={() => void loadTables()} />
					{:else if loadingTables}
						<div class="space-y-1 p-2" aria-label="Loading tables">
							{#each [1, 2, 3, 4] as _}<div class="h-9 bg-gray-50 dark:bg-neutral-900"></div>{/each}
						</div>
					{:else if filteredTables.length === 0}
						<EmptyState title="No tables found." compact />
					{:else}
						<div class="p-2" data-db-table-page>
							{#each pagedTables as table}
								<button type="button" class="app-focus flex w-full items-center rounded-md px-3 py-2 text-left font-mono text-sm transition-colors {selectedSchema === table.schema && selectedTable === table.name ? 'bg-gray-100 font-medium text-gray-950 dark:bg-neutral-800 dark:text-white' : 'text-gray-600 hover:bg-gray-50 hover:text-gray-950 dark:text-gray-300 dark:hover:bg-neutral-900 dark:hover:text-white'}" on:click={() => void chooseTable(table)}>
									<span class="truncate">{table.name}</span>
								</button>
							{/each}
						</div>
						<Pagination bind:page={tablePageIndex} pageSize={studioPageSize} totalShown={pagedTables.length} hasNext={tableHasNext} loading={loadingTables} label="Tables" />
					{/if}
				</SectionPanel>
			</div>

			<div class="min-w-0 bg-white dark:bg-neutral-950">
				<TableShell
					title={selectedTableLabel}
					description={activeFilterCount > 0 ? `${activeFilterCount} active filter${activeFilterCount === 1 ? '' : 's'} · ${primaryColumns.length > 0 ? `Primary key: ${primaryColumns.map((column) => column.name).join(', ')}` : 'No primary key'}` : primaryColumns.length > 0 ? `Primary key: ${primaryColumns.map((column) => column.name).join(', ')}` : 'Edit/delete disabled because this table has no primary key.'}
					loading={loadingRows}
					error={rowsError}
					empty={false}
					loadingRows={5}
					on:retry={() => void loadRows()}
				>
					<svelte:fragment slot="actions">
						<div class="flex w-full flex-col gap-2">
							<div class="flex w-full flex-wrap items-center gap-2">
								<input
									value={rowSearch}
									class="field min-w-[14rem] flex-1"
									placeholder="Search rows"
									aria-label="Search database rows"
									on:input={(event) => (rowSearch = (event.currentTarget as HTMLInputElement).value)}
									on:keydown={(event) => { if (event.key === 'Enter') { event.preventDefault(); void applyRowFilters(); } }}
								/>
								<ActionButton variant={filterDirty ? 'primary' : 'secondary'} size="sm" on:click={() => void applyRowFilters()} disabled={loadingRows || !filterDirty}><Filter slot="icon" class="h-4 w-4" />Apply filters</ActionButton>
								<ActionButton variant="ghost" size="sm" on:click={() => void clearRowFilters()} disabled={loadingRows || (!rowSearch && activeFilterCount === 0 && Object.values(enumFilters).filter(Boolean).length === 0)}><RotateCcw slot="icon" class="h-4 w-4" />Reset</ActionButton>
								<ActionButton variant="secondary" size="sm" on:click={() => void loadRows()} disabled={!selectedTable || loadingRows}><RefreshCw slot="icon" class="h-4 w-4" />Refresh rows</ActionButton>
								<ActionButton variant="primary" size="sm" on:click={openInsert} disabled={!writeActive || columns.length === 0}><Plus slot="icon" class="h-4 w-4" />Insert row</ActionButton>
							</div>
							{#if enumColumns.length > 0}
								<div class="grid w-full gap-2 sm:grid-cols-2 xl:grid-cols-4">
									{#each enumColumns as column}
										<label class="block min-w-0">
											<span class="field-label truncate" title={column.name}>{column.name}</span>
											<select class="field w-full" value={enumFilters[column.name] ?? ''} on:change={(event) => (enumFilters = { ...enumFilters, [column.name]: (event.currentTarget as HTMLSelectElement).value })}>
												<option value="">Any value</option>
												{#each column.enumValues ?? [] as value}<option {value}>{value}</option>{/each}
											</select>
										</label>
									{/each}
								</div>
							{/if}
						</div>
					</svelte:fragment>

					{#if !rows || rows.rows.length === 0}
						<EmptyState title={activeFilterCount > 0 ? 'No rows match these filters.' : 'No rows in this table.'} description={activeFilterCount > 0 ? 'Adjust the search or enum filters, then apply again.' : ''} compact />
					{:else}
						<div class="overflow-x-auto" data-db-row-page>
							<table class="data-table">
								<thead><tr>{#each columns as column}<th><span class="inline-flex items-center gap-1.5">{column.name}{#if column.primaryKey}<span class="font-mono text-xs font-semibold text-amber-700 dark:text-amber-300">PK</span>{/if}{#if (column.enumValues?.length ?? 0) > 0}<span class="font-mono text-xs text-gray-400 dark:text-gray-500">ENUM</span>{/if}</span></th>{/each}<th class="w-24 text-right">Actions</th></tr></thead>
								<tbody>
									{#each rows?.rows ?? [] as row, rowIndex}
										<tr>
											{#each columns as column}<td class="max-w-72 truncate font-mono text-xs text-gray-700 dark:text-gray-200" title={formatCell(row[column.name])}>{formatCell(row[column.name])}</td>{/each}
											<td class="text-right"><div class="flex justify-end gap-1"><IconButton label={`Edit database row ${pageIndex * pageSize + rowIndex + 1}`} variant="ghost" on:click={() => openEdit(row)} disabled={!writeActive || primaryColumns.length === 0}><Pencil class="h-4 w-4" aria-hidden="true" /></IconButton><IconButton label={`Delete database row ${pageIndex * pageSize + rowIndex + 1}`} variant="danger" on:click={() => openDelete(row)} disabled={!writeActive || primaryColumns.length === 0}><Trash2 class="h-4 w-4" aria-hidden="true" /></IconButton></div></td>
										</tr>
									{/each}
								</tbody>
							</table>
						</div>
					{/if}

					<svelte:fragment slot="footer"><Pagination bind:page={pageIndex} {pageSize} totalShown={rows?.rows.length ?? 0} hasNext={rows?.hasMore ?? false} loading={loadingRows} label="Rows" /></svelte:fragment>
				</TableShell>
			</div>
		</div>
	{/if}
{/if}

{#if mutationMode}
	<div class="fixed inset-0 z-50 flex items-center justify-center bg-gray-950/50 p-4">
		<div class="overlay w-full max-w-2xl overflow-hidden">
			<div class="panel-header flex items-start justify-between gap-3">
				<div><h2 class="panel-title">{mutationMode === 'insert' ? 'Insert row' : mutationMode === 'edit' ? 'Edit row' : 'Delete row'}</h2><p class="panel-description font-mono">{selectedTableLabel}</p></div>
				<IconButton label="Close database row dialog" variant="ghost" on:click={closeMutation} disabled={mutating}><X class="h-4 w-4" aria-hidden="true" /></IconButton>
			</div>
			<div class="max-h-[70vh] overflow-auto p-4">
				{#if mutationMode === 'delete'}
					<p class="text-sm leading-6 text-gray-600 dark:text-gray-300">Delete this row by primary key. This action runs immediately and cannot be undone by MyPaaS.</p>
					<div class="code-surface mt-4 space-y-1">{#each primaryColumns as column}<p><span class="font-medium">{column.name}</span>: {formatCell(selectedRow?.[column.name])}</p>{/each}</div>
				{:else}
					{#if (mutationMode === 'insert' ? insertColumns : writableColumns).some(isTemporalColumn)}
						<div class="mb-4 flex items-start gap-2 border-b border-[color:var(--workspace-divider)] pb-3 text-xs text-gray-500 dark:text-gray-400">
							<Clock3 class="mt-0.5 h-3.5 w-3.5 shrink-0" aria-hidden="true" />
							<span><strong class="font-medium text-gray-700 dark:text-gray-300">Database time</strong> is evaluated by {connection ? driverLabel(connection.driver) : 'the database'} using CURRENT_TIMESTAMP / CURRENT_DATE / CURRENT_TIME. MyPaaS does not convert it through the browser timezone.</span>
						</div>
					{/if}
					<div class="grid gap-4 sm:grid-cols-2">
						{#each mutationMode === 'insert' ? insertColumns : writableColumns as column}
							<div class="min-w-0">
								<label class="field-label" for={`db-value-${column.name}`}>
									{column.name} <span class="font-normal text-gray-400">({column.dataType})</span>
									{#if mutationMode === 'insert' && columnHasDefault(column)}<span class="ml-1 font-normal text-emerald-600 dark:text-emerald-400">default</span>{/if}
								</label>
								{#if databaseNowValues[column.name]}
									<div class="field flex w-full items-center justify-between gap-3 font-mono text-sm">
										<span class="inline-flex min-w-0 items-center gap-2"><Clock3 class="h-3.5 w-3.5 shrink-0" aria-hidden="true" />Database time</span>
										<button type="button" class="app-focus shrink-0 text-xs font-sans font-medium text-gray-500 hover:text-gray-950 dark:text-gray-400 dark:hover:text-white" on:click={() => setMutationValue(column.name, draftValues[column.name] ?? '')}>Enter value</button>
									</div>
								{:else}
									<input
										id={`db-value-${column.name}`}
										value={draftValues[column.name] ?? ''}
										class="field w-full font-mono"
										placeholder={mutationMode === 'insert' && columnHasDefault(column) && !touchedValues[column.name] ? defaultPlaceholder(column) : column.nullable ? 'nullable' : ''}
										on:input={(event) => setMutationValue(column.name, (event.currentTarget as HTMLInputElement).value)}
									/>
								{/if}
								<div class="mt-1.5 flex min-h-5 flex-wrap items-center gap-x-3 gap-y-1 text-xs">
									{#if isTemporalColumn(column) && !databaseNowValues[column.name]}
										<button type="button" class="app-focus font-medium text-gray-500 hover:text-gray-950 dark:text-gray-400 dark:hover:text-white" on:click={() => useDatabaseNow(column.name)}>Use database time</button>
									{/if}
									{#if mutationMode === 'insert' && columnHasDefault(column) && (touchedValues[column.name] || databaseNowValues[column.name])}
										<button type="button" class="app-focus font-medium text-gray-500 hover:text-gray-950 dark:text-gray-400 dark:hover:text-white" on:click={() => useDatabaseDefault(column.name)}>Use database default</button>
									{/if}
									{#if mutationMode === 'insert' && !column.nullable && !columnHasDefault(column) && !touchedValues[column.name] && !databaseNowValues[column.name]}
										<span class="text-amber-700 dark:text-amber-300">Required</span>
									{:else if mutationMode === 'insert' && columnHasDefault(column) && !touchedValues[column.name] && !databaseNowValues[column.name]}
										<span class="truncate text-gray-400" title={columnDefaultValue(column) || 'Database default'}>Using database default</span>
									{/if}
								</div>
							</div>
						{/each}
					</div>
				{/if}
			</div>
			<div class="flex items-center justify-between gap-3 border-t border-gray-100 p-4 dark:border-neutral-800">
				<div class="min-w-0 text-xs text-gray-500 dark:text-gray-400">
					{#if mutationMode === 'insert' && missingRequiredColumns.length > 0}
						Required: {missingRequiredColumns.map((column) => column.name).join(', ')}
					{:else if mutationMode === 'edit' && !mutationHasChanges}
						Change a field or choose database time before saving.
					{/if}
				</div>
				<div class="flex shrink-0 gap-2">
					<ActionButton variant="ghost" on:click={closeMutation} disabled={mutating}><X slot="icon" class="h-4 w-4" />Cancel</ActionButton>
					<ActionButton variant={mutationMode === 'delete' ? 'danger' : 'primary'} on:click={() => void submitMutation()} disabled={!canSaveMutation} loading={mutating} loadingLabel="Saving">{#if mutationMode === 'delete'}<Trash2 slot="icon" class="h-4 w-4" />{:else}<Save slot="icon" class="h-4 w-4" />{/if}{mutationMode === 'delete' ? 'Delete row' : 'Save row'}</ActionButton>
				</div>
			</div>
		</div>
	</div>
{/if}
