package deployment

import (
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/google/uuid"

	"mypaas/internal/config"
	"mypaas/internal/db"
)

func TestGeneratePerServiceEnvFilesCreatesEnvFromTemplates(t *testing.T) {
	workspace := t.TempDir()
	// apps/api/.env.example
	apiDir := filepath.Join(workspace, "apps", "api")
	if err := os.MkdirAll(apiDir, 0o750); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(filepath.Join(apiDir, ".env.example"), []byte("DATABASE_URL=postgres://localhost:5432/mydb\nAPP_PORT=3000\n"), 0o640); err != nil {
		t.Fatal(err)
	}
	// apps/worker/.env.example
	workerDir := filepath.Join(workspace, "apps", "worker")
	if err := os.MkdirAll(workerDir, 0o750); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(filepath.Join(workerDir, ".env.example"), []byte("REDIS_URL=redis://localhost:6379\nQUEUE_NAME=tasks\n"), 0o640); err != nil {
		t.Fatal(err)
	}

	var logLines []string
	log := func(line string) { logLines = append(logLines, line) }

	envs := map[string]string{
		"DATABASE_URL": "postgres://user:pass@db:5432/mydb",
		"APP_PORT":     "8080",
		"REDIS_URL":    "redis://redis:6379",
	}

	if err := generatePerServiceEnvFiles(workspace, envs, log); err != nil {
		t.Fatalf("generatePerServiceEnvFiles() error = %v", err)
	}

	// Check apps/api/.env was generated with overrides
	apiEnv, err := os.ReadFile(filepath.Join(apiDir, ".env"))
	if err != nil {
		t.Fatalf("apps/api/.env not generated: %v", err)
	}
	apiContent := string(apiEnv)
	if !strings.Contains(apiContent, "DATABASE_URL=postgres://user:pass@db:5432/mydb") {
		t.Fatalf("apps/api/.env missing DATABASE_URL override:\n%s", apiContent)
	}
	if !strings.Contains(apiContent, "APP_PORT=8080") {
		t.Fatalf("apps/api/.env missing APP_PORT override:\n%s", apiContent)
	}

	// Check apps/worker/.env was generated with overrides
	workerEnv, err := os.ReadFile(filepath.Join(workerDir, ".env"))
	if err != nil {
		t.Fatalf("apps/worker/.env not generated: %v", err)
	}
	workerContent := string(workerEnv)
	if !strings.Contains(workerContent, "REDIS_URL=redis://redis:6379") {
		t.Fatalf("apps/worker/.env missing REDIS_URL override:\n%s", workerContent)
	}

	// Check log lines mention generation
	foundLog := false
	for _, line := range logLines {
		if strings.Contains(line, "Generated") && strings.Contains(line, ".env") {
			foundLog = true
			break
		}
	}
	if !foundLog {
		t.Fatalf("expected log line about generated env files, got: %v", logLines)
	}
}

func TestGeneratePerServiceEnvFilesDoesNotOverwriteExistingEnv(t *testing.T) {
	workspace := t.TempDir()
	apiDir := filepath.Join(workspace, "apps", "api")
	if err := os.MkdirAll(apiDir, 0o750); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(filepath.Join(apiDir, ".env.example"), []byte("DATABASE_URL=postgres://localhost:5432/mydb\n"), 0o640); err != nil {
		t.Fatal(err)
	}
	// Pre-existing .env should NOT be overwritten
	if err := os.WriteFile(filepath.Join(apiDir, ".env"), []byte("DATABASE_URL=postgres://user:pass@db:5432/custom\n"), 0o600); err != nil {
		t.Fatal(err)
	}

	log := func(line string) {}
	envs := map[string]string{
		"DATABASE_URL": "postgres://overridden@db:5432/other",
	}

	if err := generatePerServiceEnvFiles(workspace, envs, log); err != nil {
		t.Fatalf("generatePerServiceEnvFiles() error = %v", err)
	}

	content, err := os.ReadFile(filepath.Join(apiDir, ".env"))
	if err != nil {
		t.Fatal(err)
	}
	if strings.Contains(string(content), "overridden") {
		t.Fatalf("existing .env was overwritten:\n%s", string(content))
	}
}

func TestGeneratePerServiceEnvFilesSkipsRootWorkspace(t *testing.T) {
	workspace := t.TempDir()
	// Root .env.example should NOT generate a root .env (that's handled by the caller)
	if err := os.WriteFile(filepath.Join(workspace, ".env.example"), []byte("FOO=bar\n"), 0o640); err != nil {
		t.Fatal(err)
	}

	log := func(line string) {}
	envs := map[string]string{"FOO": "baz"}

	if err := generatePerServiceEnvFiles(workspace, envs, log); err != nil {
		t.Fatalf("generatePerServiceEnvFiles() error = %v", err)
	}

	// Root .env should NOT be generated by this function
	if _, err := os.Stat(filepath.Join(workspace, ".env")); err == nil {
		t.Fatal("root .env should not be generated by generatePerServiceEnvFiles")
	}
}

func TestWriteComposeOverrideReplacesExistingPorts(t *testing.T) {
	path := filepath.Join(t.TempDir(), "docker-compose.mypaas.override.yml")

	if err := writeComposeOverride(path, "app", "127.0.0.1:3001:8080", 512, 0.5, "mypaas-dev", "mypaas/demo-app:abc123"); err != nil {
		t.Fatalf("writeComposeOverride() error = %v", err)
	}

	raw, err := os.ReadFile(path)
	if err != nil {
		t.Fatal(err)
	}
	content := string(raw)
	if !strings.Contains(content, "ports:") {
		t.Fatalf("override should replace compose ports, got:\n%s", content)
	}
	if !strings.Contains(content, `"127.0.0.1:3001:8080"`) {
		t.Fatalf("override missing MyPaas port mapping, got:\n%s", content)
	}
	if !strings.Contains(content, `name: "mypaas-dev"`) {
		t.Fatalf("override missing platform network, got:\n%s", content)
	}
	if !strings.Contains(content, `image: "mypaas/demo-app:abc123"`) {
		t.Fatalf("override missing immutable image tag, got:\n%s", content)
	}
}

func TestStaticCaddyPathUsesContainerPathSeparators(t *testing.T) {
	projectID := uuid.MustParse("741151a3-ee89-4357-a797-289b50be2431")
	service := &Service{
		cfg: &config.Config{
			CaddyStaticRoot: `\var\lib\mypaas\static`,
		},
	}

	got := service.staticCaddyPath(db.Project{ID: projectID})
	want := "/var/lib/mypaas/static/741151a3-ee89-4357-a797-289b50be2431"
	if got != want {
		t.Fatalf("staticCaddyPath() = %q, want %q", got, want)
	}
}

func TestIdleMetricsUsesProjectShapeWithoutDocker(t *testing.T) {
	mainService := "web"
	project := db.Project{
		DeployMode:    "compose",
		MainService:   &mainService,
		MemoryLimitMb: 256,
		Status:        "stopped",
	}

	items := idleMetrics(project)
	if len(items) != 1 {
		t.Fatalf("idleMetrics() returned %d items, want 1", len(items))
	}
	got := items[0]
	if got.Service != "web" {
		t.Fatalf("Service = %q, want web", got.Service)
	}
	if got.MemoryLimitMB != 256 {
		t.Fatalf("MemoryLimitMB = %v, want 256", got.MemoryLimitMB)
	}
	if got.CPUPercent != 0 || got.MemoryMB != 0 || got.Uptime != "n/a" {
		t.Fatalf("idle metrics should be zeroed with n/a uptime, got %+v", got)
	}
}

func TestHasLiveRuntime(t *testing.T) {
	for _, status := range []string{"running", "building"} {
		t.Run(status, func(t *testing.T) {
			if !hasLiveRuntime(status) {
				t.Fatalf("hasLiveRuntime(%q) = false, want true", status)
			}
		})
	}
	for _, status := range []string{"pending", "stopped", "crashed"} {
		t.Run(status, func(t *testing.T) {
			if hasLiveRuntime(status) {
				t.Fatalf("hasLiveRuntime(%q) = true, want false", status)
			}
		})
	}
}

func TestIdleMetricsCannotImplyRunningStatus(t *testing.T) {
	items := idleMetrics(db.Project{DeployMode: "dockerfile", Status: "stopped"})
	if len(items) != 1 {
		t.Fatalf("idleMetrics() returned %d items, want 1", len(items))
	}
	if items[0].Uptime != "n/a" {
		t.Fatalf("idle uptime = %q, want n/a", items[0].Uptime)
	}
	if hasLiveRuntime("stopped") {
		t.Fatal("stopped project must not be treated as a live runtime")
	}
}
