package staticdeploy

import (
	"compress/gzip"
	"encoding/json"
	"fmt"
	"io"
	"io/fs"
	"os"
	"path/filepath"
	"strings"

	"mypaas/internal/errs"
)

var candidateDirs = []string{"dist", "build", "out", "public", ".output/public", "_site", "site", "www", "."}

const (
	precompressMinBytes = 1024
	spaFallbackMarker   = ".mypaas-spa-fallback"
)

type packageManifest struct {
	Dependencies    map[string]string `json:"dependencies"`
	DevDependencies map[string]string `json:"devDependencies"`
}

func FindSiteRoot(workspace string) (string, string, error) {
	workspace = filepath.Clean(workspace)
	for _, rel := range candidateDirs {
		root := filepath.Join(workspace, rel)
		if hasIndex(root) {
			return root, rel, nil
		}
	}
	return "", "", errs.ErrNoDeployConfig
}

func CopyDir(src, dst string) error {
	src = filepath.Clean(src)
	dst = filepath.Clean(dst)
	if err := os.RemoveAll(dst); err != nil {
		return fmt.Errorf("clear static target: %w", err)
	}
	spaFallback := detectSPAFallback(src)
	if err := filepath.WalkDir(src, func(path string, entry fs.DirEntry, walkErr error) error {
		if walkErr != nil {
			return walkErr
		}
		if shouldSkip(path, entry) {
			if entry.IsDir() {
				return filepath.SkipDir
			}
			return nil
		}
		rel, err := filepath.Rel(src, path)
		if err != nil {
			return err
		}
		target := filepath.Join(dst, rel)
		if entry.IsDir() {
			return os.MkdirAll(target, 0750)
		}
		if entry.Type()&os.ModeSymlink != 0 {
			return nil
		}
		if err := copyFile(path, target); err != nil {
			return err
		}
		return precompressFile(target)
	}); err != nil {
		return err
	}
	if spaFallback {
		// The marker is trusted deployment metadata generated by MyPaaS. Source
		// files with the reserved .mypaas-* prefix are never copied, so an
		// application repository cannot opt itself into history fallback.
		if err := os.WriteFile(filepath.Join(dst, spaFallbackMarker), []byte("spa\n"), 0640); err != nil {
			return fmt.Errorf("write static routing marker: %w", err)
		}
	}
	return nil
}

func hasIndex(root string) bool {
	info, err := os.Stat(filepath.Join(root, "index.html"))
	return err == nil && !info.IsDir()
}

func shouldSkip(_ string, entry fs.DirEntry) bool {
	name := strings.ToLower(entry.Name())
	if strings.HasPrefix(name, ".mypaas-") {
		return true
	}
	return entry.IsDir() && (name == ".git" || name == "node_modules")
}

func copyFile(src, dst string) error {
	if err := os.MkdirAll(filepath.Dir(dst), 0750); err != nil {
		return err
	}
	in, err := os.Open(src)
	if err != nil {
		return err
	}
	defer in.Close()

	out, err := os.OpenFile(dst, os.O_CREATE|os.O_WRONLY|os.O_TRUNC, 0640)
	if err != nil {
		return err
	}

	if _, err := io.Copy(out, in); err != nil {
		_ = out.Close()
		return err
	}
	return out.Close()
}

func precompressFile(path string) error {
	if !shouldPrecompress(path) {
		return nil
	}
	info, err := os.Stat(path)
	if err != nil {
		return err
	}
	if info.Size() < precompressMinBytes {
		return nil
	}
	target := path + ".gz"
	if _, err := os.Stat(target); err == nil {
		return nil
	} else if !os.IsNotExist(err) {
		return err
	}

	in, err := os.Open(path)
	if err != nil {
		return err
	}
	defer in.Close()

	out, err := os.OpenFile(target, os.O_CREATE|os.O_WRONLY|os.O_TRUNC, 0640)
	if err != nil {
		return err
	}
	gw, err := gzip.NewWriterLevel(out, gzip.BestCompression)
	if err != nil {
		_ = out.Close()
		return err
	}
	if _, err := io.Copy(gw, in); err != nil {
		_ = gw.Close()
		_ = out.Close()
		return err
	}
	if err := gw.Close(); err != nil {
		_ = out.Close()
		return err
	}
	return out.Close()
}

func shouldPrecompress(path string) bool {
	lower := strings.ToLower(path)
	if strings.HasSuffix(lower, ".gz") || strings.HasSuffix(lower, ".br") || strings.HasSuffix(lower, ".zst") {
		return false
	}
	for _, ext := range []string{
		".html",
		".css",
		".js",
		".mjs",
		".json",
		".xml",
		".svg",
		".txt",
		".wasm",
		".map",
	} {
		if strings.HasSuffix(lower, ext) {
			return true
		}
	}
	return false
}

// detectSPAFallback decides whether a published static tree should use
// index.html as a history fallback. It deliberately recognizes only obvious
// client-rendered Vite/legacy SPA builds. Astro, Nuxt prerender, SvelteKit
// static output, and plain HTML keep normal file-server 404 semantics.
func detectSPAFallback(siteRoot string) bool {
	workspace := findPackageWorkspace(siteRoot)
	if workspace == "" {
		return false
	}
	data, err := os.ReadFile(filepath.Join(workspace, "package.json"))
	if err != nil {
		return false
	}
	var manifest packageManifest
	if err := json.Unmarshal(data, &manifest); err != nil {
		return false
	}

	if manifestHas(manifest, "astro") || manifestHas(manifest, "nuxt") || manifestHas(manifest, "next") || manifestHas(manifest, "@sveltejs/kit") {
		return false
	}
	if manifestHas(manifest, "vite") {
		if viteHasMultiPageInput(workspace) {
			return false
		}
		return manifestHas(manifest, "react") || manifestHas(manifest, "vue") || manifestHas(manifest, "svelte") || manifestHas(manifest, "preact") || manifestHas(manifest, "solid-js")
	}
	return manifestHas(manifest, "react-scripts") || manifestHas(manifest, "@vue/cli-service")
}

func findPackageWorkspace(siteRoot string) string {
	current := filepath.Clean(siteRoot)
	for i := 0; i < 4; i++ {
		if info, err := os.Stat(filepath.Join(current, "package.json")); err == nil && !info.IsDir() {
			return current
		}
		parent := filepath.Dir(current)
		if parent == current {
			break
		}
		current = parent
	}
	return ""
}

func manifestHas(manifest packageManifest, name string) bool {
	if _, ok := manifest.Dependencies[name]; ok {
		return true
	}
	_, ok := manifest.DevDependencies[name]
	return ok
}

func viteHasMultiPageInput(workspace string) bool {
	for _, name := range []string{"vite.config.js", "vite.config.mjs", "vite.config.ts", "vite.config.mts"} {
		data, err := os.ReadFile(filepath.Join(workspace, name))
		if err != nil {
			continue
		}
		normalized := strings.NewReplacer(" ", "", "\t", "", "\n", "", "\r", "").Replace(strings.ToLower(string(data)))
		if strings.Contains(normalized, "rollupoptions:") && strings.Contains(normalized, "input:") {
			return true
		}
	}
	return false
}
