services:
  directus:
    image: directus/directus:latest
    restart: unless-stopped
    environment:
      SECRET: ${SECRET}
      ADMIN_EMAIL: ${ADMIN_EMAIL}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}
      DB_CLIENT: sqlite3
      DB_FILENAME: /directus/database/data.db
      WEBSOCKETS_ENABLED: "true"
    volumes:
      - directus-database:/directus/database
      - directus-uploads:/directus/uploads
      - directus-extensions:/directus/extensions

volumes:
  directus-database:
  directus-uploads:
  directus-extensions:
