package dbstudio

import (
	"context"
	"database/sql"
	"fmt"
	"sort"
	"strings"

	"mypaas/internal/errs"
)

func scanSchemas(rows *sql.Rows) ([]Schema, error) {
	out := make([]Schema, 0)
	for rows.Next() {
		var item Schema
		if err := rows.Scan(&item.Name); err != nil {
			return nil, err
		}
		out = append(out, item)
	}
	return out, rows.Err()
}

func scanTables(rows *sql.Rows) ([]Table, error) {
	out := make([]Table, 0)
	for rows.Next() {
		var item Table
		if err := rows.Scan(&item.Schema, &item.Name); err != nil {
			return nil, err
		}
		out = append(out, item)
	}
	return out, rows.Err()
}

func scanColumns(rows *sql.Rows) ([]Column, error) {
	out := make([]Column, 0)
	for rows.Next() {
		var item Column
		var nullable, primaryKey, autoGenerated, hasDefault sql.NullBool
		var defaultValue, enumValues sql.NullString
		if err := rows.Scan(&item.Name, &item.DataType, &nullable, &primaryKey, &autoGenerated, &hasDefault, &defaultValue, &enumValues); err != nil {
			return nil, err
		}
		item.Nullable = nullable.Valid && nullable.Bool
		item.PrimaryKey = primaryKey.Valid && primaryKey.Bool
		item.AutoGenerated = autoGenerated.Valid && autoGenerated.Bool
		item.HasDefault = hasDefault.Valid && hasDefault.Bool
		if defaultValue.Valid {
			item.DefaultValue = defaultValue.String
		}
		item.EnumValues = parseEnumValues(enumValues.String)
		out = append(out, item)
	}
	return out, rows.Err()
}

func validateTable(ctx context.Context, conn *sql.DB, adapter Adapter, schema, table string) error {
	tables, err := adapter.Tables(ctx, conn, schema)
	if err != nil {
		return err
	}
	for _, item := range tables {
		if item.Schema == schema && item.Name == table {
			return nil
		}
	}
	return fmt.Errorf("%w: table is not available for DB Studio", errs.ErrValidation)
}

func mutationValues(values map[string]any, columns []Column) ([]string, []any, error) {
	allowed := columnByName(columns)
	names := make([]string, 0, len(values))
	for name := range values {
		column, ok := allowed[name]
		if !ok || column.AutoGenerated {
			continue
		}
		names = append(names, name)
	}
	sort.Strings(names)
	args := make([]any, 0, len(names))
	for _, name := range names {
		args = append(args, values[name])
	}
	return names, args, nil
}

func mutationParts(m Mutation, columns []Column) ([]string, []any, []Column, error) {
	names, values, err := mutationValues(m.Values, columns)
	if err != nil {
		return nil, nil, nil, err
	}
	nowColumns, err := mutationDatabaseNow(m.DatabaseNow, columns)
	if err != nil {
		return nil, nil, nil, err
	}
	valueSet := make(map[string]struct{}, len(names))
	for _, name := range names {
		valueSet[name] = struct{}{}
	}
	for _, column := range nowColumns {
		if _, exists := valueSet[column.Name]; exists {
			return nil, nil, nil, fmt.Errorf("%w: column %q cannot use a value and database time together", errs.ErrValidation, column.Name)
		}
	}
	return names, values, nowColumns, nil
}

func mutationDatabaseNow(names []string, columns []Column) ([]Column, error) {
	allowed := columnByName(columns)
	seen := make(map[string]struct{}, len(names))
	out := make([]Column, 0, len(names))
	for _, rawName := range names {
		name := strings.TrimSpace(rawName)
		if name == "" {
			continue
		}
		if _, exists := seen[name]; exists {
			continue
		}
		column, ok := allowed[name]
		if !ok || column.AutoGenerated {
			return nil, fmt.Errorf("%w: column %q is not writable", errs.ErrValidation, name)
		}
		if _, ok := temporalDatabaseExpression(column); !ok {
			return nil, fmt.Errorf("%w: column %q is not a temporal column", errs.ErrValidation, name)
		}
		seen[name] = struct{}{}
		out = append(out, column)
	}
	sort.Slice(out, func(i, j int) bool { return out[i].Name < out[j].Name })
	return out, nil
}

func temporalDatabaseExpression(column Column) (string, bool) {
	kind := strings.ToLower(strings.TrimSpace(column.DataType))
	switch {
	case strings.Contains(kind, "timestamp"), strings.Contains(kind, "datetime"):
		return "CURRENT_TIMESTAMP", true
	case kind == "date" || strings.HasPrefix(kind, "date("):
		return "CURRENT_DATE", true
	case strings.Contains(kind, "time"):
		return "CURRENT_TIME", true
	default:
		return "", false
	}
}

func requireMutationFields(names []string, nowColumns []Column) error {
	if len(names) == 0 && len(nowColumns) == 0 {
		return fmt.Errorf("%w: at least one writable column is required", errs.ErrValidation)
	}
	return nil
}

func quotedColumnList(columns []Column, quote func(string) string) string {
	parts := make([]string, 0, len(columns))
	for _, column := range columns {
		parts = append(parts, quote(column.Name))
	}
	return strings.Join(parts, ", ")
}

func joinQuoted(names []string, quote func(string) string) string {
	parts := make([]string, 0, len(names))
	for _, name := range names {
		parts = append(parts, quote(name))
	}
	return strings.Join(parts, ", ")
}
