package dbstudio

import (
	"context"
	"database/sql"
	"fmt"
	"strings"

	"mypaas/internal/errs"
)

func scanSchemas(rows *sql.Rows) ([]Schema, error) {
	out := make([]Schema, 0)
	for rows.Next() {
		var item Schema
		if err := rows.Scan(&item.Name); err != nil {
			return nil, err
		}
		out = append(out, item)
	}
	return out, rows.Err()
}

func scanTables(rows *sql.Rows) ([]Table, error) {
	out := make([]Table, 0)
	for rows.Next() {
		var item Table
		if err := rows.Scan(&item.Schema, &item.Name); err != nil {
			return nil, err
		}
		out = append(out, item)
	}
	return out, rows.Err()
}

func scanColumns(rows *sql.Rows) ([]Column, error) {
	out := make([]Column, 0)
	for rows.Next() {
		var item Column
		var nullable, primaryKey, autoGenerated sql.NullBool
		var enumValues sql.NullString
		if err := rows.Scan(&item.Name, &item.DataType, &nullable, &primaryKey, &autoGenerated, &enumValues); err != nil {
			return nil, err
		}
		item.Nullable = nullable.Valid && nullable.Bool
		item.PrimaryKey = primaryKey.Valid && primaryKey.Bool
		item.AutoGenerated = autoGenerated.Valid && autoGenerated.Bool
		item.EnumValues = parseEnumValues(enumValues.String)
		out = append(out, item)
	}
	return out, rows.Err()
}

func validateTable(ctx context.Context, conn *sql.DB, adapter Adapter, schema, table string) error {
	tables, err := adapter.Tables(ctx, conn, schema)
	if err != nil {
		return err
	}
	for _, item := range tables {
		if item.Schema == schema && item.Name == table {
			return nil
		}
	}
	return fmt.Errorf("%w: table is not available for DB Studio", errs.ErrValidation)
}

func mutationValues(values map[string]any, columns []Column) ([]string, []any, error) {
	allowed := columnByName(columns)
	names := make([]string, 0, len(values))
	args := make([]any, 0, len(values))
	for name, value := range values {
		column, ok := allowed[name]
		if !ok || column.AutoGenerated {
			continue
		}
		names = append(names, name)
		args = append(args, value)
	}
	if len(names) == 0 {
		return nil, nil, fmt.Errorf("%w: at least one writable column is required", errs.ErrValidation)
	}
	return names, args, nil
}

func quotedColumnList(columns []Column, quote func(string) string) string {
	parts := make([]string, 0, len(columns))
	for _, column := range columns {
		parts = append(parts, quote(column.Name))
	}
	return strings.Join(parts, ", ")
}

func joinQuoted(names []string, quote func(string) string) string {
	parts := make([]string, 0, len(names))
	for _, name := range names {
		parts = append(parts, quote(name))
	}
	return strings.Join(parts, ", ")
}
