package dbstudio

import (
	"context"
	"database/sql"
	"fmt"
	"math/big"
	"sort"
	"strconv"
	"strings"

	"github.com/google/uuid"

	"mypaas/internal/errs"
)

func scanSchemas(rows *sql.Rows) ([]Schema, error) {
	out := make([]Schema, 0)
	for rows.Next() {
		var item Schema
		if err := rows.Scan(&item.Name); err != nil {
			return nil, err
		}
		out = append(out, item)
	}
	return out, rows.Err()
}

func scanTables(rows *sql.Rows) ([]Table, error) {
	out := make([]Table, 0)
	for rows.Next() {
		var item Table
		if err := rows.Scan(&item.Schema, &item.Name); err != nil {
			return nil, err
		}
		out = append(out, item)
	}
	return out, rows.Err()
}

func scanColumns(rows *sql.Rows) ([]Column, error) {
	out := make([]Column, 0)
	for rows.Next() {
		var item Column
		var nullable, primaryKey, autoGenerated, hasDefault sql.NullBool
		var defaultValue, enumValues sql.NullString
		if err := rows.Scan(&item.Name, &item.DataType, &nullable, &primaryKey, &autoGenerated, &hasDefault, &defaultValue, &enumValues); err != nil {
			return nil, err
		}
		item.Nullable = nullable.Valid && nullable.Bool
		item.PrimaryKey = primaryKey.Valid && primaryKey.Bool
		item.AutoGenerated = autoGenerated.Valid && autoGenerated.Bool
		item.HasDefault = hasDefault.Valid && hasDefault.Bool
		if defaultValue.Valid {
			item.DefaultValue = defaultValue.String
		}
		item.EnumValues = parseEnumValues(enumValues.String)
		out = append(out, item)
	}
	return out, rows.Err()
}

func validateTable(ctx context.Context, conn *sql.DB, adapter Adapter, schema, table string) error {
	tables, err := adapter.Tables(ctx, conn, schema)
	if err != nil {
		return err
	}
	for _, item := range tables {
		if item.Schema == schema && item.Name == table {
			return nil
		}
	}
	return fmt.Errorf("%w: table is not available for DB Studio", errs.ErrValidation)
}

type mutationValueKind string

const (
	mutationUnsupported mutationValueKind = "unsupported"
	mutationText        mutationValueKind = "text"
	mutationInteger     mutationValueKind = "integer"
	mutationDecimal     mutationValueKind = "decimal"
	mutationFloat       mutationValueKind = "float"
	mutationBoolean     mutationValueKind = "boolean"
	mutationUUID        mutationValueKind = "uuid"
	mutationEnum        mutationValueKind = "enum"
	mutationTemporal    mutationValueKind = "temporal"
)

func mutationColumnKind(column Column) mutationValueKind {
	if len(column.EnumValues) > 0 {
		return mutationEnum
	}
	if _, ok := temporalDatabaseExpression(column); ok {
		return mutationTemporal
	}

	kind := strings.ToLower(strings.TrimSpace(column.DataType))
	switch {
	case strings.Contains(kind, "json"),
		strings.Contains(kind, "blob"),
		strings.Contains(kind, "binary"),
		strings.Contains(kind, "bytea"),
		strings.Contains(kind, "geometry"),
		strings.Contains(kind, "geography"),
		strings.Contains(kind, "xml"),
		strings.Contains(kind, "array"),
		strings.Contains(kind, "range"):
		return mutationUnsupported
	case kind == "boolean", kind == "bool", strings.HasPrefix(kind, "tinyint(1)"):
		return mutationBoolean
	case strings.Contains(kind, "uuid"):
		return mutationUUID
	case strings.Contains(kind, "int"):
		return mutationInteger
	case strings.Contains(kind, "numeric"), strings.Contains(kind, "decimal"):
		return mutationDecimal
	case strings.Contains(kind, "real"), strings.Contains(kind, "double"), strings.Contains(kind, "float"):
		return mutationFloat
	case strings.Contains(kind, "char"), strings.Contains(kind, "text"), strings.Contains(kind, "clob"):
		return mutationText
	default:
		return mutationUnsupported
	}
}

func mutationValues(values map[string]any, columns []Column) ([]string, []any, error) {
	allowed := columnByName(columns)
	names := make([]string, 0, len(values))
	for name := range values {
		column, ok := allowed[name]
		if !ok {
			return nil, nil, fmt.Errorf("%w: column %q is not available", errs.ErrValidation, name)
		}
		if column.AutoGenerated {
			return nil, nil, fmt.Errorf("%w: generated column %q is not writable", errs.ErrValidation, name)
		}
		if column.PrimaryKey {
			return nil, nil, fmt.Errorf("%w: primary key column %q is not writable", errs.ErrValidation, name)
		}
		names = append(names, name)
	}
	sort.Strings(names)

	args := make([]any, 0, len(names))
	for _, name := range names {
		column := allowed[name]
		value, err := normalizeMutationValue(column, values[name])
		if err != nil {
			return nil, nil, err
		}
		args = append(args, value)
	}
	return names, args, nil
}

func normalizeMutationValue(column Column, raw any) (any, error) {
	kind := mutationColumnKind(column)
	if kind == mutationUnsupported {
		return nil, fmt.Errorf("%w: column %q uses unsupported write type %q", errs.ErrValidation, column.Name, column.DataType)
	}
	if raw == nil {
		if !column.Nullable {
			return nil, fmt.Errorf("%w: column %q cannot be NULL", errs.ErrValidation, column.Name)
		}
		return nil, nil
	}
	if kind == mutationTemporal {
		return nil, fmt.Errorf("%w: manual temporal values are disabled for column %q; use database time instead", errs.ErrValidation, column.Name)
	}

	text, ok := raw.(string)
	if !ok {
		switch typed := raw.(type) {
		case bool:
			if kind == mutationBoolean {
				return typed, nil
			}
		case int:
			text, ok = strconv.FormatInt(int64(typed), 10), true
		case int8:
			text, ok = strconv.FormatInt(int64(typed), 10), true
		case int16:
			text, ok = strconv.FormatInt(int64(typed), 10), true
		case int32:
			text, ok = strconv.FormatInt(int64(typed), 10), true
		case int64:
			text, ok = strconv.FormatInt(typed, 10), true
		case uint:
			text, ok = strconv.FormatUint(uint64(typed), 10), true
		case uint8:
			text, ok = strconv.FormatUint(uint64(typed), 10), true
		case uint16:
			text, ok = strconv.FormatUint(uint64(typed), 10), true
		case uint32:
			text, ok = strconv.FormatUint(uint64(typed), 10), true
		case uint64:
			text, ok = strconv.FormatUint(typed, 10), true
		case float32:
			text, ok = strconv.FormatFloat(float64(typed), 'g', -1, 32), true
		case float64:
			text, ok = strconv.FormatFloat(typed, 'g', -1, 64), true
		}
	}
	if !ok {
		return nil, fmt.Errorf("%w: column %q requires a string-compatible value", errs.ErrValidation, column.Name)
	}

	switch kind {
	case mutationText:
		return text, nil
	case mutationEnum:
		if !containsString(column.EnumValues, text) {
			return nil, fmt.Errorf("%w: value is not valid for enum column %q", errs.ErrValidation, column.Name)
		}
		return text, nil
	case mutationBoolean:
		switch strings.ToLower(strings.TrimSpace(text)) {
		case "true", "1":
			return true, nil
		case "false", "0":
			return false, nil
		default:
			return nil, fmt.Errorf("%w: column %q requires true or false", errs.ErrValidation, column.Name)
		}
	case mutationInteger:
		if strings.Contains(strings.ToLower(column.DataType), "unsigned") {
			value, err := strconv.ParseUint(strings.TrimSpace(text), 10, 64)
			if err != nil {
				return nil, fmt.Errorf("%w: column %q requires an unsigned integer", errs.ErrValidation, column.Name)
			}
			return value, nil
		}
		value, err := strconv.ParseInt(strings.TrimSpace(text), 10, 64)
		if err != nil {
			return nil, fmt.Errorf("%w: column %q requires an integer", errs.ErrValidation, column.Name)
		}
		return value, nil
	case mutationDecimal:
		value := strings.TrimSpace(text)
		if value == "" {
			return nil, fmt.Errorf("%w: column %q requires a decimal value", errs.ErrValidation, column.Name)
		}
		if _, ok := new(big.Rat).SetString(value); !ok {
			return nil, fmt.Errorf("%w: column %q requires a decimal value", errs.ErrValidation, column.Name)
		}
		return value, nil
	case mutationFloat:
		value, err := strconv.ParseFloat(strings.TrimSpace(text), 64)
		if err != nil {
			return nil, fmt.Errorf("%w: column %q requires a numeric value", errs.ErrValidation, column.Name)
		}
		return value, nil
	case mutationUUID:
		value, err := uuid.Parse(strings.TrimSpace(text))
		if err != nil {
			return nil, fmt.Errorf("%w: column %q requires a valid UUID", errs.ErrValidation, column.Name)
		}
		return value.String(), nil
	default:
		return nil, fmt.Errorf("%w: column %q is not writable", errs.ErrValidation, column.Name)
	}
}

func mutationParts(m Mutation, columns []Column) ([]string, []any, []Column, error) {
	names, values, err := mutationValues(m.Values, columns)
	if err != nil {
		return nil, nil, nil, err
	}
	nowColumns, err := mutationDatabaseNow(m.DatabaseNow, columns)
	if err != nil {
		return nil, nil, nil, err
	}
	valueSet := make(map[string]struct{}, len(names))
	for _, name := range names {
		valueSet[name] = struct{}{}
	}
	for _, column := range nowColumns {
		if _, exists := valueSet[column.Name]; exists {
			return nil, nil, nil, fmt.Errorf("%w: column %q cannot use a value and database time together", errs.ErrValidation, column.Name)
		}
	}
	return names, values, nowColumns, nil
}

func mutationDatabaseNow(names []string, columns []Column) ([]Column, error) {
	allowed := columnByName(columns)
	seen := make(map[string]struct{}, len(names))
	out := make([]Column, 0, len(names))
	for _, rawName := range names {
		name := strings.TrimSpace(rawName)
		if name == "" {
			continue
		}
		if _, exists := seen[name]; exists {
			continue
		}
		column, ok := allowed[name]
		if !ok || column.AutoGenerated || column.PrimaryKey {
			return nil, fmt.Errorf("%w: column %q is not writable", errs.ErrValidation, name)
		}
		if _, ok := temporalDatabaseExpression(column); !ok {
			return nil, fmt.Errorf("%w: column %q is not a temporal column", errs.ErrValidation, name)
		}
		seen[name] = struct{}{}
		out = append(out, column)
	}
	sort.Slice(out, func(i, j int) bool { return out[i].Name < out[j].Name })
	return out, nil
}

func temporalDatabaseExpression(column Column) (string, bool) {
	kind := strings.ToLower(strings.TrimSpace(column.DataType))
	switch {
	case strings.Contains(kind, "timestamp"), strings.Contains(kind, "datetime"):
		return "CURRENT_TIMESTAMP", true
	case kind == "date" || strings.HasPrefix(kind, "date("):
		return "CURRENT_DATE", true
	case strings.Contains(kind, "time"):
		return "CURRENT_TIME", true
	default:
		return "", false
	}
}

func requireMutationFields(names []string, nowColumns []Column) error {
	if len(names) == 0 && len(nowColumns) == 0 {
		return fmt.Errorf("%w: at least one writable column is required", errs.ErrValidation)
	}
	return nil
}

func quotedColumnList(columns []Column, quote func(string) string) string {
	parts := make([]string, 0, len(columns))
	for _, column := range columns {
		parts = append(parts, quote(column.Name))
	}
	return strings.Join(parts, ", ")
}

func joinQuoted(names []string, quote func(string) string) string {
	parts := make([]string, 0, len(names))
	for _, name := range names {
		parts = append(parts, quote(name))
	}
	return strings.Join(parts, ", ")
}
