package dbstudio

import (
	"reflect"
	"strings"
	"testing"
)

func mutationTestColumns() []Column {
	return []Column{
		{Name: "id", DataType: "bigint", PrimaryKey: true, AutoGenerated: true, HasDefault: true, DefaultValue: "nextval('events_id_seq'::regclass)"},
		{Name: "name", DataType: "text"},
		{Name: "created_at", DataType: "timestamp with time zone", HasDefault: true, DefaultValue: "CURRENT_TIMESTAMP"},
		{Name: "event_date", DataType: "date"},
	}
}

func TestMutationValuesAreDeterministicAndSkipGeneratedColumns(t *testing.T) {
	names, values, err := mutationValues(map[string]any{
		"name": "demo",
		"id":   99,
		"nope": "ignored",
	}, mutationTestColumns())
	if err != nil {
		t.Fatal(err)
	}
	if !reflect.DeepEqual(names, []string{"name"}) {
		t.Fatalf("unexpected names: %#v", names)
	}
	if !reflect.DeepEqual(values, []any{"demo"}) {
		t.Fatalf("unexpected values: %#v", values)
	}
}

func TestMutationDatabaseNowAcceptsOnlyTemporalWritableColumns(t *testing.T) {
	columns, err := mutationDatabaseNow([]string{"created_at", "event_date", "created_at"}, mutationTestColumns())
	if err != nil {
		t.Fatal(err)
	}
	if got := []string{columns[0].Name, columns[1].Name}; !reflect.DeepEqual(got, []string{"created_at", "event_date"}) {
		t.Fatalf("unexpected database-now columns: %#v", got)
	}
	if _, err := mutationDatabaseNow([]string{"name"}, mutationTestColumns()); err == nil || !strings.Contains(err.Error(), "not a temporal column") {
		t.Fatalf("expected temporal validation error, got %v", err)
	}
}

func TestMutationPartsRejectsValueAndDatabaseNowOverlap(t *testing.T) {
	_, _, _, err := mutationParts(Mutation{
		Values:      map[string]any{"created_at": "manual"},
		DatabaseNow: []string{"created_at"},
	}, mutationTestColumns())
	if err == nil || !strings.Contains(err.Error(), "cannot use a value and database time together") {
		t.Fatalf("expected overlap validation error, got %v", err)
	}
}

func TestPostgresInsertSupportsDefaultsAndDatabaseTime(t *testing.T) {
	columns := mutationTestColumns()

	sqlText, args, err := postgresInsertSQL(Mutation{Schema: "public", Table: "events"}, columns)
	if err != nil {
		t.Fatal(err)
	}
	if sqlText != `INSERT INTO "public"."events" DEFAULT VALUES` || len(args) != 0 {
		t.Fatalf("unexpected default insert: %q %#v", sqlText, args)
	}

	sqlText, args, err = postgresInsertSQL(Mutation{
		Schema:      "public",
		Table:       "events",
		Values:      map[string]any{"name": "demo"},
		DatabaseNow: []string{"created_at"},
	}, columns)
	if err != nil {
		t.Fatal(err)
	}
	want := `INSERT INTO "public"."events" ("name", "created_at") VALUES ($1, CURRENT_TIMESTAMP)`
	if sqlText != want || !reflect.DeepEqual(args, []any{"demo"}) {
		t.Fatalf("unexpected postgres insert: %q %#v", sqlText, args)
	}
}

func TestMySQLAndSQLiteDefaultOnlyInsert(t *testing.T) {
	columns := mutationTestColumns()
	mysqlSQL, mysqlArgs, err := mysqlInsertSQL(Mutation{Schema: "app", Table: "events"}, columns)
	if err != nil {
		t.Fatal(err)
	}
	if mysqlSQL != "INSERT INTO `app`.`events` () VALUES ()" || len(mysqlArgs) != 0 {
		t.Fatalf("unexpected mysql default insert: %q %#v", mysqlSQL, mysqlArgs)
	}

	sqliteSQL, sqliteArgs, err := sqliteInsertSQL(Mutation{Schema: "main", Table: "events"}, columns)
	if err != nil {
		t.Fatal(err)
	}
	if sqliteSQL != `INSERT INTO "events" DEFAULT VALUES` || len(sqliteArgs) != 0 {
		t.Fatalf("unexpected sqlite default insert: %q %#v", sqliteSQL, sqliteArgs)
	}
}

func TestMySQLUpdateCanUseDatabaseTimeWithoutBrowserTimezone(t *testing.T) {
	sqlText, args, err := mysqlUpdateSQL(Mutation{
		Schema:      "app",
		Table:       "events",
		DatabaseNow: []string{"created_at"},
		PrimaryKey:  map[string]any{"id": 7},
	}, mutationTestColumns())
	if err != nil {
		t.Fatal(err)
	}
	want := "UPDATE `app`.`events` SET `created_at` = CURRENT_TIMESTAMP WHERE `id` = ?"
	if sqlText != want || !reflect.DeepEqual(args, []any{7}) {
		t.Fatalf("unexpected mysql update: %q %#v", sqlText, args)
	}
}

func TestUpdateStillRequiresAnExplicitMutation(t *testing.T) {
	_, _, err := postgresUpdateSQL(Mutation{
		Schema:     "public",
		Table:      "events",
		PrimaryKey: map[string]any{"id": 1},
	}, mutationTestColumns())
	if err == nil || !strings.Contains(err.Error(), "at least one writable column") {
		t.Fatalf("expected empty update validation error, got %v", err)
	}
}
