package dbstudio

import (
	"reflect"
	"strings"
	"testing"
)

func mutationTestColumns() []Column {
	return []Column{
		{Name: "id", DataType: "bigint", PrimaryKey: true, AutoGenerated: true, HasDefault: true, DefaultValue: "nextval('events_id_seq'::regclass)"},
		{Name: "name", DataType: "text"},
		{Name: "count", DataType: "integer"},
		{Name: "active", DataType: "boolean"},
		{Name: "external_id", DataType: "uuid"},
		{Name: "status", DataType: "USER-DEFINED", EnumValues: []string{"draft", "published"}},
		{Name: "notes", DataType: "text", Nullable: true},
		{Name: "metadata", DataType: "jsonb", Nullable: true},
		{Name: "created_at", DataType: "timestamp with time zone", Nullable: true, HasDefault: true, DefaultValue: "CURRENT_TIMESTAMP"},
		{Name: "event_date", DataType: "date"},
	}
}

func TestMutationValuesAreDeterministicAndTyped(t *testing.T) {
	names, values, err := mutationValues(map[string]any{
		"name":        "demo",
		"count":       "42",
		"active":      "true",
		"external_id": "11111111-1111-1111-1111-111111111111",
		"status":      "draft",
	}, mutationTestColumns())
	if err != nil {
		t.Fatal(err)
	}
	wantNames := []string{"active", "count", "external_id", "name", "status"}
	if !reflect.DeepEqual(names, wantNames) {
		t.Fatalf("unexpected names: %#v", names)
	}
	if values[0] != true || values[1] != int64(42) || values[2] != "11111111-1111-1111-1111-111111111111" || values[3] != "demo" || values[4] != "draft" {
		t.Fatalf("unexpected typed values: %#v", values)
	}
}

func TestMutationValuesFailClosedForUnknownGeneratedAndPrimaryKeyColumns(t *testing.T) {
	columns := mutationTestColumns()

	if _, _, err := mutationValues(map[string]any{"nope": "ignored"}, columns); err == nil || !strings.Contains(err.Error(), "not available") {
		t.Fatalf("expected unknown-column validation error, got %v", err)
	}
	if _, _, err := mutationValues(map[string]any{"id": "99"}, columns); err == nil || !strings.Contains(err.Error(), "generated column") {
		t.Fatalf("expected generated-column validation error, got %v", err)
	}

	manualPK := []Column{{Name: "code", DataType: "text", PrimaryKey: true}}
	if _, _, err := mutationValues(map[string]any{"code": "next"}, manualPK); err == nil || !strings.Contains(err.Error(), "primary key") {
		t.Fatalf("expected primary-key validation error, got %v", err)
	}
}

func TestMutationValuesRejectUnsupportedAndInvalidValues(t *testing.T) {
	columns := mutationTestColumns()

	if _, _, err := mutationValues(map[string]any{"metadata": `{"a":1}`}, columns); err == nil || !strings.Contains(err.Error(), "unsupported write type") {
		t.Fatalf("expected unsupported-type validation error, got %v", err)
	}
	if _, _, err := mutationValues(map[string]any{"count": "abc"}, columns); err == nil || !strings.Contains(err.Error(), "requires an integer") {
		t.Fatalf("expected integer validation error, got %v", err)
	}
	if _, _, err := mutationValues(map[string]any{"status": "deleted"}, columns); err == nil || !strings.Contains(err.Error(), "enum column") {
		t.Fatalf("expected enum validation error, got %v", err)
	}
	if _, _, err := mutationValues(map[string]any{"created_at": "2026-09-05T10:00:00Z"}, columns); err == nil || !strings.Contains(err.Error(), "manual temporal values are disabled") {
		t.Fatalf("expected temporal validation error, got %v", err)
	}
}

func TestMutationValuesSupportExplicitNullableNull(t *testing.T) {
	names, values, err := mutationValues(map[string]any{"notes": nil}, mutationTestColumns())
	if err != nil {
		t.Fatal(err)
	}
	if !reflect.DeepEqual(names, []string{"notes"}) || len(values) != 1 || values[0] != nil {
		t.Fatalf("unexpected null mutation: %#v %#v", names, values)
	}

	if _, _, err := mutationValues(map[string]any{"name": nil}, mutationTestColumns()); err == nil || !strings.Contains(err.Error(), "cannot be NULL") {
		t.Fatalf("expected non-nullable validation error, got %v", err)
	}
}

func TestMutationDatabaseNowAcceptsOnlyTemporalWritableColumns(t *testing.T) {
	columns, err := mutationDatabaseNow([]string{"created_at", "event_date", "created_at"}, mutationTestColumns())
	if err != nil {
		t.Fatal(err)
	}
	if got := []string{columns[0].Name, columns[1].Name}; !reflect.DeepEqual(got, []string{"created_at", "event_date"}) {
		t.Fatalf("unexpected database-now columns: %#v", got)
	}
	if _, err := mutationDatabaseNow([]string{"name"}, mutationTestColumns()); err == nil || !strings.Contains(err.Error(), "not a temporal column") {
		t.Fatalf("expected temporal validation error, got %v", err)
	}
}

func TestMutationPartsRejectsValueAndDatabaseNowOverlap(t *testing.T) {
	_, _, _, err := mutationParts(Mutation{
		Values:      map[string]any{"created_at": nil},
		DatabaseNow: []string{"created_at"},
	}, mutationTestColumns())
	if err == nil || !strings.Contains(err.Error(), "cannot use a value and database time together") {
		t.Fatalf("expected overlap validation error, got %v", err)
	}
}

func TestPostgresInsertSupportsDefaultsAndDatabaseTime(t *testing.T) {
	columns := mutationTestColumns()

	sqlText, args, err := postgresInsertSQL(Mutation{Schema: "public", Table: "events"}, columns)
	if err != nil {
		t.Fatal(err)
	}
	if sqlText != `INSERT INTO "public"."events" DEFAULT VALUES` || len(args) != 0 {
		t.Fatalf("unexpected default insert: %q %#v", sqlText, args)
	}

	sqlText, args, err = postgresInsertSQL(Mutation{
		Schema:      "public",
		Table:       "events",
		Values:      map[string]any{"name": "demo"},
		DatabaseNow: []string{"created_at"},
	}, columns)
	if err != nil {
		t.Fatal(err)
	}
	want := `INSERT INTO "public"."events" ("name", "created_at") VALUES ($1, CURRENT_TIMESTAMP)`
	if sqlText != want || !reflect.DeepEqual(args, []any{"demo"}) {
		t.Fatalf("unexpected postgres insert: %q %#v", sqlText, args)
	}
}

func TestMySQLAndSQLiteDefaultOnlyInsert(t *testing.T) {
	columns := mutationTestColumns()
	mysqlSQL, mysqlArgs, err := mysqlInsertSQL(Mutation{Schema: "app", Table: "events"}, columns)
	if err != nil {
		t.Fatal(err)
	}
	if mysqlSQL != "INSERT INTO `app`.`events` () VALUES ()" || len(mysqlArgs) != 0 {
		t.Fatalf("unexpected mysql default insert: %q %#v", mysqlSQL, mysqlArgs)
	}

	sqliteSQL, sqliteArgs, err := sqliteInsertSQL(Mutation{Schema: "main", Table: "events"}, columns)
	if err != nil {
		t.Fatal(err)
	}
	if sqliteSQL != `INSERT INTO "events" DEFAULT VALUES` || len(sqliteArgs) != 0 {
		t.Fatalf("unexpected sqlite default insert: %q %#v", sqliteSQL, sqliteArgs)
	}
}

func TestMySQLUpdateCanUseDatabaseTimeWithoutBrowserTimezone(t *testing.T) {
	sqlText, args, err := mysqlUpdateSQL(Mutation{
		Schema:      "app",
		Table:       "events",
		DatabaseNow: []string{"created_at"},
		PrimaryKey:  map[string]any{"id": 7},
	}, mutationTestColumns())
	if err != nil {
		t.Fatal(err)
	}
	want := "UPDATE `app`.`events` SET `created_at` = CURRENT_TIMESTAMP WHERE `id` = ?"
	if sqlText != want || !reflect.DeepEqual(args, []any{7}) {
		t.Fatalf("unexpected mysql update: %q %#v", sqlText, args)
	}
}

func TestUpdateStillRequiresAnExplicitMutation(t *testing.T) {
	_, _, err := postgresUpdateSQL(Mutation{
		Schema:     "public",
		Table:      "events",
		PrimaryKey: map[string]any{"id": 1},
	}, mutationTestColumns())
	if err == nil || !strings.Contains(err.Error(), "at least one writable column") {
		t.Fatalf("expected empty update validation error, got %v", err)
	}
}
