package dbstudio

import (
	"context"
	"database/sql"
	"fmt"
	"strings"

	_ "modernc.org/sqlite"

	"mypaas/internal/errs"
)

type sqliteAdapter struct{}

func openSQLiteDatabase(ctx context.Context, databasePath string) (*sql.DB, error) {
	databasePath = strings.TrimSpace(databasePath)
	if databasePath == "" {
		return nil, fmt.Errorf("%w: SQLite database path is required", errs.ErrValidation)
	}
	conn, err := sql.Open("sqlite", "file:"+databasePath+"?mode=rw&_pragma=foreign_keys(1)&_pragma=busy_timeout(5000)")
	if err != nil {
		return nil, err
	}
	conn.SetMaxOpenConns(1)
	conn.SetMaxIdleConns(1)
	if err := conn.PingContext(ctx); err != nil {
		_ = conn.Close()
		return nil, err
	}
	return conn, nil
}

func (sqliteAdapter) Schemas(context.Context, *sql.DB) ([]Schema, error) {
	return []Schema{{Name: "main"}}, nil
}

func (sqliteAdapter) Tables(ctx context.Context, conn *sql.DB, schema string) ([]Table, error) {
	if err := validateSQLiteSchema(schema); err != nil {
		return nil, err
	}
	rows, err := conn.QueryContext(ctx, `
SELECT 'main', name
FROM sqlite_schema
WHERE type = 'table'
  AND name NOT LIKE 'sqlite_%'
ORDER BY name`)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	return scanTables(rows)
}

func (a sqliteAdapter) Columns(ctx context.Context, conn *sql.DB, schema, table string) ([]Column, error) {
	if err := validateTable(ctx, conn, a, schema, table); err != nil {
		return nil, err
	}
	rows, err := conn.QueryContext(ctx, `
SELECT name, COALESCE(type, ''), "notnull", pk
FROM pragma_table_info(?)
ORDER BY cid`, table)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	columns := make([]Column, 0)
	for rows.Next() {
		var item Column
		var notNull, primaryPosition int
		if err := rows.Scan(&item.Name, &item.DataType, &notNull, &primaryPosition); err != nil {
			return nil, err
		}
		item.PrimaryKey = primaryPosition > 0
		item.Nullable = !item.PrimaryKey && notNull == 0
		columns = append(columns, item)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}

	if len(primaryKeyColumns(columns)) == 1 {
		for index := range columns {
			if columns[index].PrimaryKey && strings.EqualFold(strings.TrimSpace(columns[index].DataType), "INTEGER") {
				withoutRowID, err := sqliteTableWithoutRowID(ctx, conn, table)
				if err != nil {
					return nil, err
				}
				columns[index].AutoGenerated = !withoutRowID
			}
		}
	}
	return columns, nil
}

func (a sqliteAdapter) TableDetails(ctx context.Context, conn *sql.DB, schema, table string) (TableDetails, error) {
	columns, err := a.Columns(ctx, conn, schema, table)
	if err != nil {
		return TableDetails{}, err
	}
	foreignKeys, err := sqliteForeignKeys(ctx, conn, table)
	if err != nil {
		return TableDetails{}, err
	}
	indexes, err := sqliteIndexes(ctx, conn, table)
	if err != nil {
		return TableDetails{}, err
	}
	constraints := sqliteConstraints(columns, foreignKeys, indexes)
	return TableDetails{
		Schema: schema, Name: table, Columns: columns,
		ForeignKeys: foreignKeys, Indexes: indexes, Constraints: constraints,
	}, nil
}

func (a sqliteAdapter) Rows(ctx context.Context, conn *sql.DB, query RowQuery) (RowPage, error) {
	columns, err := a.Columns(ctx, conn, query.Schema, query.Table)
	if err != nil {
		return RowPage{}, err
	}
	limit := normalizeLimit(query.Limit)
	offset := normalizeOffset(query.Offset)
	sqlText, args, err := sqliteSelectSQL(query.Table, columns, query, limit, offset)
	if err != nil {
		return RowPage{}, err
	}
	rows, err := conn.QueryContext(ctx, sqlText, args...)
	if err != nil {
		return RowPage{}, err
	}
	defer rows.Close()
	return scanRows(rows, columns, limit, offset)
}

func (a sqliteAdapter) Insert(ctx context.Context, conn *sql.DB, mutation Mutation) error {
	columns, err := a.Columns(ctx, conn, mutation.Schema, mutation.Table)
	if err != nil {
		return err
	}
	sqlText, args, err := sqliteInsertSQL(mutation, columns)
	if err != nil {
		return err
	}
	_, err = conn.ExecContext(ctx, sqlText, args...)
	return err
}

func (a sqliteAdapter) Update(ctx context.Context, conn *sql.DB, mutation Mutation) error {
	columns, err := a.Columns(ctx, conn, mutation.Schema, mutation.Table)
	if err != nil {
		return err
	}
	sqlText, args, err := sqliteUpdateSQL(mutation, columns)
	if err != nil {
		return err
	}
	_, err = conn.ExecContext(ctx, sqlText, args...)
	return err
}

func (a sqliteAdapter) Delete(ctx context.Context, conn *sql.DB, mutation Mutation) error {
	columns, err := a.Columns(ctx, conn, mutation.Schema, mutation.Table)
	if err != nil {
		return err
	}
	sqlText, args, err := sqliteDeleteSQL(mutation, columns)
	if err != nil {
		return err
	}
	_, err = conn.ExecContext(ctx, sqlText, args...)
	return err
}

func validateSQLiteSchema(schema string) error {
	if strings.TrimSpace(schema) != "main" {
		return fmt.Errorf("%w: SQLite exposes only the main schema", errs.ErrValidation)
	}
	return nil
}

func quoteSQLiteIdent(value string) string {
	return `"` + strings.ReplaceAll(value, `"`, `""`) + `"`
}

func sqliteSelectSQL(table string, columns []Column, query RowQuery, limit, offset int) (string, []any, error) {
	if err := validateSQLiteSchema(query.Schema); err != nil {
		return "", nil, err
	}
	where, args, err := sqliteWhereClause(columns, query)
	if err != nil {
		return "", nil, err
	}
	order := sqliteOrderClause(columns)
	args = append(args, limit+1, offset)
	return fmt.Sprintf("SELECT %s FROM %s%s%s LIMIT ? OFFSET ?",
		quotedColumnList(columns, quoteSQLiteIdent), quoteSQLiteIdent(table), where, order), args, nil
}

func sqliteWhereClause(columns []Column, query RowQuery) (string, []any, error) {
	clauses := make([]string, 0)
	args := make([]any, 0)

	filters, err := enumFilters(query.Filters, columns)
	if err != nil {
		return "", nil, err
	}
	for _, filter := range filters {
		clauses = append(clauses, quoteSQLiteIdent(filter.Column.Name)+" = ?")
		args = append(args, filter.Value)
	}

	search, err := normalizeRowSearch(query.Search)
	if err != nil {
		return "", nil, err
	}
	if search != "" {
		searchable := searchableColumns(columns)
		if len(searchable) == 0 {
			clauses = append(clauses, "1 = 0")
		} else {
			pattern := likePattern(search)
			parts := make([]string, 0, len(searchable))
			for _, column := range searchable {
				parts = append(parts, "CAST("+quoteSQLiteIdent(column.Name)+" AS TEXT) LIKE ? ESCAPE '\\'")
				args = append(args, pattern)
			}
			clauses = append(clauses, "("+strings.Join(parts, " OR ")+")")
		}
	}
	if len(clauses) == 0 {
		return "", args, nil
	}
	return " WHERE " + strings.Join(clauses, " AND "), args, nil
}

func sqliteOrderClause(columns []Column) string {
	pks := primaryKeyColumns(columns)
	if len(pks) == 0 {
		return ""
	}
	parts := make([]string, 0, len(pks))
	for _, column := range pks {
		parts = append(parts, quoteSQLiteIdent(column.Name))
	}
	return " ORDER BY " + strings.Join(parts, ", ")
}

func sqliteInsertSQL(m Mutation, columns []Column) (string, []any, error) {
	if err := validateSQLiteSchema(m.Schema); err != nil {
		return "", nil, err
	}
	names, values, err := mutationValues(m.Values, columns)
	if err != nil {
		return "", nil, err
	}
	return fmt.Sprintf("INSERT INTO %s (%s) VALUES (%s)", quoteSQLiteIdent(m.Table),
		joinQuoted(names, quoteSQLiteIdent), sqlitePlaceholders(len(names))), values, nil
}

func sqliteUpdateSQL(m Mutation, columns []Column) (string, []any, error) {
	if err := validateSQLiteSchema(m.Schema); err != nil {
		return "", nil, err
	}
	names, values, err := mutationValues(m.Values, columns)
	if err != nil {
		return "", nil, err
	}
	where, pkValues, err := sqlitePrimaryKeyWhere(m.PrimaryKey, columns)
	if err != nil {
		return "", nil, err
	}
	return fmt.Sprintf("UPDATE %s SET %s WHERE %s", quoteSQLiteIdent(m.Table), sqliteSetList(names), where), append(values, pkValues...), nil
}

func sqliteDeleteSQL(m Mutation, columns []Column) (string, []any, error) {
	if err := validateSQLiteSchema(m.Schema); err != nil {
		return "", nil, err
	}
	where, values, err := sqlitePrimaryKeyWhere(m.PrimaryKey, columns)
	if err != nil {
		return "", nil, err
	}
	return fmt.Sprintf("DELETE FROM %s WHERE %s", quoteSQLiteIdent(m.Table), where), values, nil
}

func sqlitePlaceholders(count int) string {
	parts := make([]string, count)
	for index := range parts {
		parts[index] = "?"
	}
	return strings.Join(parts, ", ")
}

func sqliteSetList(names []string) string {
	parts := make([]string, 0, len(names))
	for _, name := range names {
		parts = append(parts, quoteSQLiteIdent(name)+" = ?")
	}
	return strings.Join(parts, ", ")
}

func sqlitePrimaryKeyWhere(values map[string]any, columns []Column) (string, []any, error) {
	pks := primaryKeyColumns(columns)
	if len(pks) == 0 {
		return "", nil, fmt.Errorf("%w: table needs a primary key for write actions", errs.ErrValidation)
	}
	parts := make([]string, 0, len(pks))
	args := make([]any, 0, len(pks))
	for _, column := range pks {
		value, ok := values[column.Name]
		if !ok {
			return "", nil, fmt.Errorf("%w: primary key %q is required", errs.ErrValidation, column.Name)
		}
		parts = append(parts, quoteSQLiteIdent(column.Name)+" = ?")
		args = append(args, value)
	}
	return strings.Join(parts, " AND "), args, nil
}

func sqliteTableWithoutRowID(ctx context.Context, conn *sql.DB, table string) (bool, error) {
	var definition sql.NullString
	if err := conn.QueryRowContext(ctx, `SELECT sql FROM sqlite_schema WHERE type = 'table' AND name = ?`, table).Scan(&definition); err != nil {
		return false, err
	}
	return strings.Contains(strings.ToUpper(definition.String), "WITHOUT ROWID"), nil
}

func sqliteForeignKeys(ctx context.Context, conn *sql.DB, table string) ([]ForeignKey, error) {
	rows, err := conn.QueryContext(ctx, `
SELECT id, seq, "from", "table", "to", on_update, on_delete
FROM pragma_foreign_key_list(?)
ORDER BY id, seq`, table)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	out := make([]ForeignKey, 0)
	for rows.Next() {
		var id, seq int
		var item ForeignKey
		if err := rows.Scan(&id, &seq, &item.Column, &item.ReferencedTable, &item.ReferencedColumn, &item.OnUpdate, &item.OnDelete); err != nil {
			return nil, err
		}
		item.Name = fmt.Sprintf("fk_%d_%d", id, seq)
		item.ReferencedSchema = "main"
		out = append(out, item)
	}
	return out, rows.Err()
}

func sqliteIndexes(ctx context.Context, conn *sql.DB, table string) ([]Index, error) {
	rows, err := conn.QueryContext(ctx, `
SELECT name, "unique", origin
FROM pragma_index_list(?)
ORDER BY seq`, table)
	if err != nil {
		return nil, err
	}

	out := make([]Index, 0)
	for rows.Next() {
		var item Index
		var unique int
		var origin string
		if err := rows.Scan(&item.Name, &unique, &origin); err != nil {
			_ = rows.Close()
			return nil, err
		}
		item.Unique = unique != 0
		item.Primary = origin == "pk"
		item.Method = "btree"
		out = append(out, item)
	}
	if err := rows.Err(); err != nil {
		_ = rows.Close()
		return nil, err
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}

	for index := range out {
		columnRows, err := conn.QueryContext(ctx, `SELECT name FROM pragma_index_info(?) ORDER BY seqno`, out[index].Name)
		if err != nil {
			return nil, err
		}
		columns := make([]string, 0)
		for columnRows.Next() {
			var column sql.NullString
			if err := columnRows.Scan(&column); err != nil {
				_ = columnRows.Close()
				return nil, err
			}
			if column.Valid && strings.TrimSpace(column.String) != "" {
				columns = append(columns, column.String)
			}
		}
		if err := columnRows.Err(); err != nil {
			_ = columnRows.Close()
			return nil, err
		}
		_ = columnRows.Close()
		out[index].Columns = columns

		var definition sql.NullString
		_ = conn.QueryRowContext(ctx, `SELECT sql FROM sqlite_schema WHERE type = 'index' AND name = ?`, out[index].Name).Scan(&definition)
		out[index].Definition = definition.String
	}
	return out, nil
}

func sqliteConstraints(columns []Column, foreignKeys []ForeignKey, indexes []Index) []Constraint {
	out := make([]Constraint, 0)
	pks := primaryKeyColumns(columns)
	if len(pks) > 0 {
		names := make([]string, 0, len(pks))
		for _, column := range pks {
			names = append(names, column.Name)
		}
		out = append(out, Constraint{Name: "primary_key", Type: "PRIMARY KEY", Columns: names})
	}
	for _, index := range indexes {
		if index.Unique && !index.Primary {
			out = append(out, Constraint{Name: index.Name, Type: "UNIQUE", Columns: append([]string(nil), index.Columns...), Definition: index.Definition})
		}
	}
	for _, fk := range foreignKeys {
		out = append(out, Constraint{Name: fk.Name, Type: "FOREIGN KEY", Columns: []string{fk.Column}})
	}
	return out
}
