package dbstudio

import (
	"context"
	"database/sql"
	"time"
)

type DriverID string

const (
	DriverPostgres DriverID = "postgres"
	DriverMySQL    DriverID = "mysql"
	DriverMariaDB  DriverID = "mariadb"
)

type Connection struct {
	Driver   DriverID `json:"driver"`
	Host     string   `json:"host"`
	Port     int      `json:"port"`
	Database string   `json:"database"`
	User     string   `json:"user"`
	Source   string   `json:"source"`
	DSN      string   `json:"-"`
}

type Status struct {
	Configured  bool          `json:"configured"`
	Connected   bool          `json:"connected"`
	Message     string        `json:"message"`
	Connection  *Connection   `json:"connection"`
	WriteAccess *WriteSession `json:"writeAccess"`
}

type WriteSession struct {
	ID        string    `json:"id"`
	ExpiresAt time.Time `json:"expiresAt"`
}

type Schema struct {
	Name string `json:"name"`
}

type Table struct {
	Schema string `json:"schema"`
	Name   string `json:"name"`
}

type Column struct {
	Name          string `json:"name"`
	DataType      string `json:"dataType"`
	Nullable      bool   `json:"nullable"`
	PrimaryKey    bool   `json:"primaryKey"`
	AutoGenerated bool   `json:"autoGenerated"`
}

type RowPage struct {
	Columns []Column         `json:"columns"`
	Rows    []map[string]any `json:"rows"`
	Limit   int              `json:"limit"`
	Offset  int              `json:"offset"`
	HasMore bool             `json:"hasMore"`
}

type RowQuery struct {
	Schema string
	Table  string
	Limit  int
	Offset int
}

type Mutation struct {
	Schema     string         `json:"schema"`
	Table      string         `json:"table"`
	Values     map[string]any `json:"values"`
	PrimaryKey map[string]any `json:"primaryKey"`
}

type Adapter interface {
	Schemas(context.Context, *sql.DB) ([]Schema, error)
	Tables(context.Context, *sql.DB, string) ([]Table, error)
	Columns(context.Context, *sql.DB, string, string) ([]Column, error)
	Rows(context.Context, *sql.DB, RowQuery) (RowPage, error)
	Insert(context.Context, *sql.DB, Mutation) error
	Update(context.Context, *sql.DB, Mutation) error
	Delete(context.Context, *sql.DB, Mutation) error
}
