// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: api_tokens.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const authenticateAPIToken = `-- name: AuthenticateAPIToken :one
UPDATE api_tokens
SET last_used_at = NOW()
WHERE token_hash = $1
  AND revoked_at IS NULL
  AND (expires_at IS NULL OR expires_at > NOW())
RETURNING id, user_id, name, token_hash, token_prefix, scopes, expires_at, last_used_at, created_at, revoked_at
`

func (q *Queries) AuthenticateAPIToken(ctx context.Context, tokenHash []byte) (ApiToken, error) {
	row := q.db.QueryRow(ctx, authenticateAPIToken, tokenHash)
	var i ApiToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.TokenHash,
		&i.TokenPrefix,
		&i.Scopes,
		&i.ExpiresAt,
		&i.LastUsedAt,
		&i.CreatedAt,
		&i.RevokedAt,
	)
	return i, err
}

const createAPIToken = `-- name: CreateAPIToken :one
INSERT INTO api_tokens (user_id, name, token_hash, token_prefix, scopes, expires_at)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, user_id, name, token_hash, token_prefix, scopes, expires_at, last_used_at, created_at, revoked_at
`

type CreateAPITokenParams struct {
	UserID      uuid.UUID        `json:"user_id"`
	Name        string           `json:"name"`
	TokenHash   []byte           `json:"token_hash"`
	TokenPrefix string           `json:"token_prefix"`
	Scopes      []string         `json:"scopes"`
	ExpiresAt   pgtype.Timestamp `json:"expires_at"`
}

func (q *Queries) CreateAPIToken(ctx context.Context, arg CreateAPITokenParams) (ApiToken, error) {
	row := q.db.QueryRow(ctx, createAPIToken,
		arg.UserID,
		arg.Name,
		arg.TokenHash,
		arg.TokenPrefix,
		arg.Scopes,
		arg.ExpiresAt,
	)
	var i ApiToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.TokenHash,
		&i.TokenPrefix,
		&i.Scopes,
		&i.ExpiresAt,
		&i.LastUsedAt,
		&i.CreatedAt,
		&i.RevokedAt,
	)
	return i, err
}

const listAPITokens = `-- name: ListAPITokens :many
SELECT id, user_id, name, token_hash, token_prefix, scopes, expires_at, last_used_at, created_at, revoked_at
FROM api_tokens
WHERE user_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListAPITokens(ctx context.Context, userID uuid.UUID) ([]ApiToken, error) {
	rows, err := q.db.Query(ctx, listAPITokens, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ApiToken
	for rows.Next() {
		var i ApiToken
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.TokenHash,
			&i.TokenPrefix,
			&i.Scopes,
			&i.ExpiresAt,
			&i.LastUsedAt,
			&i.CreatedAt,
			&i.RevokedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeAPIToken = `-- name: RevokeAPIToken :execrows
UPDATE api_tokens
SET revoked_at = COALESCE(revoked_at, NOW())
WHERE id = $1
  AND user_id = $2
`

type RevokeAPITokenParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) RevokeAPIToken(ctx context.Context, arg RevokeAPITokenParams) (int64, error) {
	result, err := q.db.Exec(ctx, revokeAPIToken, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const revokeActiveAPITokensByName = `-- name: RevokeActiveAPITokensByName :exec
UPDATE api_tokens
SET revoked_at = NOW()
WHERE user_id = $1
  AND name = $2
  AND revoked_at IS NULL
`

type RevokeActiveAPITokensByNameParams struct {
	UserID uuid.UUID `json:"user_id"`
	Name   string    `json:"name"`
}

func (q *Queries) RevokeActiveAPITokensByName(ctx context.Context, arg RevokeActiveAPITokensByNameParams) error {
	_, err := q.db.Exec(ctx, revokeActiveAPITokensByName, arg.UserID, arg.Name)
	return err
}
