// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: db_studio_sessions.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createDBStudioSession = `-- name: CreateDBStudioSession :one
INSERT INTO db_studio_sessions (
    project_id, user_id, mode, expires_at
) VALUES ($1, $2, 'write', $3)
RETURNING id, project_id, user_id, mode, expires_at, revoked_at, created_at
`

type CreateDBStudioSessionParams struct {
	ProjectID uuid.UUID        `json:"project_id"`
	UserID    uuid.UUID        `json:"user_id"`
	ExpiresAt pgtype.Timestamp `json:"expires_at"`
}

func (q *Queries) CreateDBStudioSession(ctx context.Context, arg CreateDBStudioSessionParams) (DbStudioSession, error) {
	row := q.db.QueryRow(ctx, createDBStudioSession, arg.ProjectID, arg.UserID, arg.ExpiresAt)
	var i DbStudioSession
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.UserID,
		&i.Mode,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getActiveDBStudioSession = `-- name: GetActiveDBStudioSession :one
SELECT id, project_id, user_id, mode, expires_at, revoked_at, created_at
FROM db_studio_sessions
WHERE project_id = $1
  AND user_id = $2
  AND mode = 'write'
  AND revoked_at IS NULL
  AND expires_at > NOW()
ORDER BY expires_at DESC
LIMIT 1
`

type GetActiveDBStudioSessionParams struct {
	ProjectID uuid.UUID `json:"project_id"`
	UserID    uuid.UUID `json:"user_id"`
}

func (q *Queries) GetActiveDBStudioSession(ctx context.Context, arg GetActiveDBStudioSessionParams) (DbStudioSession, error) {
	row := q.db.QueryRow(ctx, getActiveDBStudioSession, arg.ProjectID, arg.UserID)
	var i DbStudioSession
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.UserID,
		&i.Mode,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const revokeDBStudioSession = `-- name: RevokeDBStudioSession :exec
UPDATE db_studio_sessions
SET revoked_at = NOW()
WHERE id = $1
  AND project_id = $2
  AND user_id = $3
  AND revoked_at IS NULL
`

type RevokeDBStudioSessionParams struct {
	ID        uuid.UUID `json:"id"`
	ProjectID uuid.UUID `json:"project_id"`
	UserID    uuid.UUID `json:"user_id"`
}

func (q *Queries) RevokeDBStudioSession(ctx context.Context, arg RevokeDBStudioSessionParams) error {
	_, err := q.db.Exec(ctx, revokeDBStudioSession, arg.ID, arg.ProjectID, arg.UserID)
	return err
}
