// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: deployments.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const appendBuildLog = `-- name: AppendBuildLog :exec
UPDATE deployments
SET build_log = COALESCE(build_log, '') || $2
WHERE id = $1
`

type AppendBuildLogParams struct {
	ID       uuid.UUID `json:"id"`
	BuildLog *string   `json:"build_log"`
}

func (q *Queries) AppendBuildLog(ctx context.Context, arg AppendBuildLogParams) error {
	_, err := q.db.Exec(ctx, appendBuildLog, arg.ID, arg.BuildLog)
	return err
}

const countDeploymentsByProject = `-- name: CountDeploymentsByProject :one
SELECT COUNT(*) FROM deployments WHERE project_id = $1
`

func (q *Queries) CountDeploymentsByProject(ctx context.Context, projectID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countDeploymentsByProject, projectID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createDeployment = `-- name: CreateDeployment :one
INSERT INTO deployments (
    project_id, commit_sha, commit_message,
    status, triggered_by, triggered_by_user_id, image_tag
) VALUES ($1, $2, $3, 'queued', $4, $5, $6)
RETURNING id, project_id, commit_sha, commit_message, status, build_log, error_msg, image_tag,
          triggered_by, triggered_by_user_id, started_at, finished_at
`

type CreateDeploymentParams struct {
	ProjectID         uuid.UUID   `json:"project_id"`
	CommitSha         *string     `json:"commit_sha"`
	CommitMessage     *string     `json:"commit_message"`
	TriggeredBy       string      `json:"triggered_by"`
	TriggeredByUserID pgtype.UUID `json:"triggered_by_user_id"`
	ImageTag          *string     `json:"image_tag"`
}

func (q *Queries) CreateDeployment(ctx context.Context, arg CreateDeploymentParams) (Deployment, error) {
	row := q.db.QueryRow(ctx, createDeployment,
		arg.ProjectID,
		arg.CommitSha,
		arg.CommitMessage,
		arg.TriggeredBy,
		arg.TriggeredByUserID,
		arg.ImageTag,
	)
	var i Deployment
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.CommitSha,
		&i.CommitMessage,
		&i.Status,
		&i.BuildLog,
		&i.ErrorMsg,
		&i.ImageTag,
		&i.TriggeredBy,
		&i.TriggeredByUserID,
		&i.StartedAt,
		&i.FinishedAt,
	)
	return i, err
}

const failDeployment = `-- name: FailDeployment :exec
UPDATE deployments
SET status      = 'failed',
    error_msg   = $2,
    finished_at = NOW()
WHERE id = $1
`

type FailDeploymentParams struct {
	ID       uuid.UUID `json:"id"`
	ErrorMsg *string   `json:"error_msg"`
}

func (q *Queries) FailDeployment(ctx context.Context, arg FailDeploymentParams) error {
	_, err := q.db.Exec(ctx, failDeployment, arg.ID, arg.ErrorMsg)
	return err
}

const failInterruptedDeployments = `-- name: FailInterruptedDeployments :exec
UPDATE deployments
SET status      = 'failed',
    error_msg   = $1,
    finished_at = NOW()
WHERE status IN ('queued', 'cloning', 'building', 'starting')
`

func (q *Queries) FailInterruptedDeployments(ctx context.Context, errorMsg *string) error {
	_, err := q.db.Exec(ctx, failInterruptedDeployments, errorMsg)
	return err
}

const finishDeployment = `-- name: FinishDeployment :exec
UPDATE deployments
SET status      = $2,
    finished_at = NOW()
WHERE id = $1
`

type FinishDeploymentParams struct {
	ID     uuid.UUID `json:"id"`
	Status string    `json:"status"`
}

func (q *Queries) FinishDeployment(ctx context.Context, arg FinishDeploymentParams) error {
	_, err := q.db.Exec(ctx, finishDeployment, arg.ID, arg.Status)
	return err
}

const getActiveDeploymentByProject = `-- name: GetActiveDeploymentByProject :one
SELECT id, project_id, commit_sha, commit_message, status, build_log, error_msg, image_tag,
       triggered_by, triggered_by_user_id, started_at, finished_at
FROM deployments
WHERE project_id = $1
  AND status IN ('queued', 'cloning', 'building', 'starting')
ORDER BY started_at DESC
LIMIT 1
`

func (q *Queries) GetActiveDeploymentByProject(ctx context.Context, projectID uuid.UUID) (Deployment, error) {
	row := q.db.QueryRow(ctx, getActiveDeploymentByProject, projectID)
	var i Deployment
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.CommitSha,
		&i.CommitMessage,
		&i.Status,
		&i.BuildLog,
		&i.ErrorMsg,
		&i.ImageTag,
		&i.TriggeredBy,
		&i.TriggeredByUserID,
		&i.StartedAt,
		&i.FinishedAt,
	)
	return i, err
}

const getDeploymentByID = `-- name: GetDeploymentByID :one
SELECT id, project_id, commit_sha, commit_message, status, build_log, error_msg, image_tag,
       triggered_by, triggered_by_user_id, started_at, finished_at
FROM deployments
WHERE id = $1
`

func (q *Queries) GetDeploymentByID(ctx context.Context, id uuid.UUID) (Deployment, error) {
	row := q.db.QueryRow(ctx, getDeploymentByID, id)
	var i Deployment
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.CommitSha,
		&i.CommitMessage,
		&i.Status,
		&i.BuildLog,
		&i.ErrorMsg,
		&i.ImageTag,
		&i.TriggeredBy,
		&i.TriggeredByUserID,
		&i.StartedAt,
		&i.FinishedAt,
	)
	return i, err
}

const getLatestRunningDeployment = `-- name: GetLatestRunningDeployment :one
SELECT id, project_id, commit_sha, commit_message, status, build_log, error_msg, image_tag,
       triggered_by, triggered_by_user_id, started_at, finished_at
FROM deployments
WHERE project_id = $1 AND status = 'running'
ORDER BY started_at DESC
LIMIT 1
`

func (q *Queries) GetLatestRunningDeployment(ctx context.Context, projectID uuid.UUID) (Deployment, error) {
	row := q.db.QueryRow(ctx, getLatestRunningDeployment, projectID)
	var i Deployment
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.CommitSha,
		&i.CommitMessage,
		&i.Status,
		&i.BuildLog,
		&i.ErrorMsg,
		&i.ImageTag,
		&i.TriggeredBy,
		&i.TriggeredByUserID,
		&i.StartedAt,
		&i.FinishedAt,
	)
	return i, err
}

const getRollbackTarget = `-- name: GetRollbackTarget :one
SELECT id, project_id, commit_sha, commit_message, status, build_log, error_msg, image_tag,
       triggered_by, triggered_by_user_id, started_at, finished_at
FROM deployments
WHERE project_id = $1
  AND status     = 'running'
  AND id        != $2
ORDER BY started_at DESC
LIMIT 1
`

type GetRollbackTargetParams struct {
	ProjectID uuid.UUID `json:"project_id"`
	ID        uuid.UUID `json:"id"`
}

// Returns the most recent successfully-run deployment that is not the current one.
func (q *Queries) GetRollbackTarget(ctx context.Context, arg GetRollbackTargetParams) (Deployment, error) {
	row := q.db.QueryRow(ctx, getRollbackTarget, arg.ProjectID, arg.ID)
	var i Deployment
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.CommitSha,
		&i.CommitMessage,
		&i.Status,
		&i.BuildLog,
		&i.ErrorMsg,
		&i.ImageTag,
		&i.TriggeredBy,
		&i.TriggeredByUserID,
		&i.StartedAt,
		&i.FinishedAt,
	)
	return i, err
}

const listDeploymentsByProject = `-- name: ListDeploymentsByProject :many
SELECT id, project_id, commit_sha, commit_message, status, build_log, error_msg, image_tag,
       triggered_by, triggered_by_user_id, started_at, finished_at
FROM deployments
WHERE project_id = $1
ORDER BY started_at DESC
LIMIT $2 OFFSET $3
`

type ListDeploymentsByProjectParams struct {
	ProjectID uuid.UUID `json:"project_id"`
	Limit     int32     `json:"limit"`
	Offset    int32     `json:"offset"`
}

func (q *Queries) ListDeploymentsByProject(ctx context.Context, arg ListDeploymentsByProjectParams) ([]Deployment, error) {
	rows, err := q.db.Query(ctx, listDeploymentsByProject, arg.ProjectID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Deployment
	for rows.Next() {
		var i Deployment
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.CommitSha,
			&i.CommitMessage,
			&i.Status,
			&i.BuildLog,
			&i.ErrorMsg,
			&i.ImageTag,
			&i.TriggeredBy,
			&i.TriggeredByUserID,
			&i.StartedAt,
			&i.FinishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const pruneOldDeployments = `-- name: PruneOldDeployments :exec
DELETE FROM deployments
WHERE deployments.project_id = $1
  AND deployments.id NOT IN (
      SELECT kept.id FROM deployments AS kept
      WHERE kept.project_id = $1
      ORDER BY kept.started_at DESC
      LIMIT 20
  )
`

// Keep the 20 most recent; delete the rest.
func (q *Queries) PruneOldDeployments(ctx context.Context, projectID uuid.UUID) error {
	_, err := q.db.Exec(ctx, pruneOldDeployments, projectID)
	return err
}

const setDeploymentBuildInfo = `-- name: SetDeploymentBuildInfo :exec
UPDATE deployments
SET commit_sha = $2,
    commit_message = $3,
    image_tag = $4
WHERE id = $1
`

type SetDeploymentBuildInfoParams struct {
	ID            uuid.UUID `json:"id"`
	CommitSha     *string   `json:"commit_sha"`
	CommitMessage *string   `json:"commit_message"`
	ImageTag      *string   `json:"image_tag"`
}

func (q *Queries) SetDeploymentBuildInfo(ctx context.Context, arg SetDeploymentBuildInfoParams) error {
	_, err := q.db.Exec(ctx, setDeploymentBuildInfo,
		arg.ID,
		arg.CommitSha,
		arg.CommitMessage,
		arg.ImageTag,
	)
	return err
}

const updateDeploymentStatus = `-- name: UpdateDeploymentStatus :exec
UPDATE deployments
SET status = $2
WHERE id = $1
`

type UpdateDeploymentStatusParams struct {
	ID     uuid.UUID `json:"id"`
	Status string    `json:"status"`
}

func (q *Queries) UpdateDeploymentStatus(ctx context.Context, arg UpdateDeploymentStatusParams) error {
	_, err := q.db.Exec(ctx, updateDeploymentStatus, arg.ID, arg.Status)
	return err
}
