// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: env_vars.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const deleteAllEnvVars = `-- name: DeleteAllEnvVars :exec
DELETE FROM env_vars
WHERE project_id = $1
`

func (q *Queries) DeleteAllEnvVars(ctx context.Context, projectID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteAllEnvVars, projectID)
	return err
}

const deleteEnvVar = `-- name: DeleteEnvVar :exec
DELETE FROM env_vars
WHERE project_id = $1 AND key = $2
`

type DeleteEnvVarParams struct {
	ProjectID uuid.UUID `json:"project_id"`
	Key       string    `json:"key"`
}

func (q *Queries) DeleteEnvVar(ctx context.Context, arg DeleteEnvVarParams) error {
	_, err := q.db.Exec(ctx, deleteEnvVar, arg.ProjectID, arg.Key)
	return err
}

const getEnvVar = `-- name: GetEnvVar :one
SELECT id, project_id, key, value_encrypted, value_nonce, created_at, updated_at
FROM env_vars
WHERE project_id = $1 AND key = $2
`

type GetEnvVarParams struct {
	ProjectID uuid.UUID `json:"project_id"`
	Key       string    `json:"key"`
}

func (q *Queries) GetEnvVar(ctx context.Context, arg GetEnvVarParams) (EnvVar, error) {
	row := q.db.QueryRow(ctx, getEnvVar, arg.ProjectID, arg.Key)
	var i EnvVar
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Key,
		&i.ValueEncrypted,
		&i.ValueNonce,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listEnvVarsByProject = `-- name: ListEnvVarsByProject :many
SELECT id, project_id, key, value_encrypted, value_nonce, created_at, updated_at
FROM env_vars
WHERE project_id = $1
ORDER BY key
`

func (q *Queries) ListEnvVarsByProject(ctx context.Context, projectID uuid.UUID) ([]EnvVar, error) {
	rows, err := q.db.Query(ctx, listEnvVarsByProject, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EnvVar
	for rows.Next() {
		var i EnvVar
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Key,
			&i.ValueEncrypted,
			&i.ValueNonce,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertEnvVar = `-- name: UpsertEnvVar :one
INSERT INTO env_vars (project_id, key, value_encrypted, value_nonce)
VALUES ($1, $2, $3, $4)
ON CONFLICT (project_id, key) DO UPDATE
    SET value_encrypted = EXCLUDED.value_encrypted,
        value_nonce     = EXCLUDED.value_nonce,
        updated_at      = NOW()
RETURNING id, project_id, key, value_encrypted, value_nonce, created_at, updated_at
`

type UpsertEnvVarParams struct {
	ProjectID      uuid.UUID `json:"project_id"`
	Key            string    `json:"key"`
	ValueEncrypted string    `json:"value_encrypted"`
	ValueNonce     string    `json:"value_nonce"`
}

func (q *Queries) UpsertEnvVar(ctx context.Context, arg UpsertEnvVarParams) (EnvVar, error) {
	row := q.db.QueryRow(ctx, upsertEnvVar,
		arg.ProjectID,
		arg.Key,
		arg.ValueEncrypted,
		arg.ValueNonce,
	)
	var i EnvVar
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Key,
		&i.ValueEncrypted,
		&i.ValueNonce,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
