// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"net/netip"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type AuditLog struct {
	ID           uuid.UUID        `json:"id"`
	UserID       pgtype.UUID      `json:"user_id"`
	Action       string           `json:"action"`
	ResourceType *string          `json:"resource_type"`
	ResourceID   pgtype.UUID      `json:"resource_id"`
	Metadata     []byte           `json:"metadata"`
	IpAddress    *netip.Addr      `json:"ip_address"`
	UserAgent    *string          `json:"user_agent"`
	CreatedAt    pgtype.Timestamp `json:"created_at"`
}

type DbStudioSession struct {
	ID        uuid.UUID        `json:"id"`
	ProjectID uuid.UUID        `json:"project_id"`
	UserID    uuid.UUID        `json:"user_id"`
	Mode      string           `json:"mode"`
	ExpiresAt pgtype.Timestamp `json:"expires_at"`
	RevokedAt pgtype.Timestamp `json:"revoked_at"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
}

type Deployment struct {
	ID                uuid.UUID        `json:"id"`
	ProjectID         uuid.UUID        `json:"project_id"`
	CommitSha         *string          `json:"commit_sha"`
	CommitMessage     *string          `json:"commit_message"`
	Status            string           `json:"status"`
	BuildLog          *string          `json:"build_log"`
	ErrorMsg          *string          `json:"error_msg"`
	ImageTag          *string          `json:"image_tag"`
	TriggeredBy       string           `json:"triggered_by"`
	TriggeredByUserID pgtype.UUID      `json:"triggered_by_user_id"`
	StartedAt         pgtype.Timestamp `json:"started_at"`
	FinishedAt        pgtype.Timestamp `json:"finished_at"`
}

type EnvVar struct {
	ID             uuid.UUID        `json:"id"`
	ProjectID      uuid.UUID        `json:"project_id"`
	Key            string           `json:"key"`
	ValueEncrypted string           `json:"value_encrypted"`
	ValueNonce     string           `json:"value_nonce"`
	CreatedAt      pgtype.Timestamp `json:"created_at"`
	UpdatedAt      pgtype.Timestamp `json:"updated_at"`
}

type PortRegistry struct {
	Port       int32            `json:"port"`
	ProjectID  pgtype.UUID      `json:"project_id"`
	Status     string           `json:"status"`
	AssignedAt pgtype.Timestamp `json:"assigned_at"`
}

type Project struct {
	ID                 uuid.UUID        `json:"id"`
	UserID             uuid.UUID        `json:"user_id"`
	Name               string           `json:"name"`
	RepoUrl            string           `json:"repo_url"`
	Branch             string           `json:"branch"`
	Subdomain          string           `json:"subdomain"`
	DeployMode         string           `json:"deploy_mode"`
	MainService        *string          `json:"main_service"`
	AppPort            int32            `json:"app_port"`
	WebhookSecret      string           `json:"webhook_secret"`
	AllocatedPort      *int32           `json:"allocated_port"`
	MemoryLimitMb      int32            `json:"memory_limit_mb"`
	CpuLimit           pgtype.Numeric   `json:"cpu_limit"`
	Status             string           `json:"status"`
	ActiveDeploymentID pgtype.UUID      `json:"active_deployment_id"`
	CreatedAt          pgtype.Timestamp `json:"created_at"`
	UpdatedAt          pgtype.Timestamp `json:"updated_at"`
	DeletedAt          pgtype.Timestamp `json:"deleted_at"`
	ResourceProfile    string           `json:"resource_profile"`
}

type User struct {
	ID             uuid.UUID        `json:"id"`
	Email          string           `json:"email"`
	GithubID       *string          `json:"github_id"`
	GithubUsername *string          `json:"github_username"`
	AvatarUrl      *string          `json:"avatar_url"`
	Role           string           `json:"role"`
	CreatedAt      pgtype.Timestamp `json:"created_at"`
	LastLoginAt    pgtype.Timestamp `json:"last_login_at"`
}

type WebhookDelivery struct {
	ID               uuid.UUID        `json:"id"`
	ProjectID        uuid.UUID        `json:"project_id"`
	GithubDeliveryID *string          `json:"github_delivery_id"`
	SignatureValid   bool             `json:"signature_valid"`
	EventType        *string          `json:"event_type"`
	Branch           *string          `json:"branch"`
	Processed        bool             `json:"processed"`
	DeploymentID     pgtype.UUID      `json:"deployment_id"`
	ReceivedAt       pgtype.Timestamp `json:"received_at"`
}
