// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: port_registry.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const acquireAvailablePort = `-- name: AcquireAvailablePort :one
SELECT port
FROM port_registry
WHERE status = 'available'
ORDER BY port
LIMIT 1
FOR UPDATE SKIP LOCKED
`

// Lock one available port for atomic allocation. Must be called inside a transaction.
// Caller updates the row with SetPortInUse immediately after.
func (q *Queries) AcquireAvailablePort(ctx context.Context) (int32, error) {
	row := q.db.QueryRow(ctx, acquireAvailablePort)
	var port int32
	err := row.Scan(&port)
	return port, err
}

const getPortByProject = `-- name: GetPortByProject :one
SELECT port, project_id, status, assigned_at
FROM port_registry
WHERE project_id = $1
`

func (q *Queries) GetPortByProject(ctx context.Context, projectID pgtype.UUID) (PortRegistry, error) {
	row := q.db.QueryRow(ctx, getPortByProject, projectID)
	var i PortRegistry
	err := row.Scan(
		&i.Port,
		&i.ProjectID,
		&i.Status,
		&i.AssignedAt,
	)
	return i, err
}

const listInUsePorts = `-- name: ListInUsePorts :many
SELECT port, project_id, status, assigned_at
FROM port_registry
WHERE status = 'in_use'
ORDER BY port
`

func (q *Queries) ListInUsePorts(ctx context.Context) ([]PortRegistry, error) {
	rows, err := q.db.Query(ctx, listInUsePorts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PortRegistry
	for rows.Next() {
		var i PortRegistry
		if err := rows.Scan(
			&i.Port,
			&i.ProjectID,
			&i.Status,
			&i.AssignedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const releasePort = `-- name: ReleasePort :exec
UPDATE port_registry
SET status      = 'available',
    project_id  = NULL,
    assigned_at = NULL
WHERE port = $1
`

func (q *Queries) ReleasePort(ctx context.Context, port int32) error {
	_, err := q.db.Exec(ctx, releasePort, port)
	return err
}

const releasePortByProject = `-- name: ReleasePortByProject :exec
UPDATE port_registry
SET status      = 'available',
    project_id  = NULL,
    assigned_at = NULL
WHERE project_id = $1
`

func (q *Queries) ReleasePortByProject(ctx context.Context, projectID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, releasePortByProject, projectID)
	return err
}

const setPortInUse = `-- name: SetPortInUse :exec
UPDATE port_registry
SET status      = 'in_use',
    project_id  = $2,
    assigned_at = NOW()
WHERE port = $1
`

type SetPortInUseParams struct {
	Port      int32       `json:"port"`
	ProjectID pgtype.UUID `json:"project_id"`
}

func (q *Queries) SetPortInUse(ctx context.Context, arg SetPortInUseParams) error {
	_, err := q.db.Exec(ctx, setPortInUse, arg.Port, arg.ProjectID)
	return err
}
