// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: projects.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countProjectsByUser = `-- name: CountProjectsByUser :one
SELECT COUNT(*)
FROM projects
WHERE user_id = $1
  AND deleted_at IS NULL
`

func (q *Queries) CountProjectsByUser(ctx context.Context, userID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countProjectsByUser, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createProject = `-- name: CreateProject :one
INSERT INTO projects (
    user_id, name, repo_url, branch, subdomain, deploy_mode,
    main_service, app_port, webhook_secret, memory_limit_mb, cpu_limit
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
RETURNING id, user_id, name, repo_url, branch, subdomain, deploy_mode, main_service,
          app_port, webhook_secret, allocated_port, memory_limit_mb, cpu_limit,
          status, active_deployment_id, created_at, updated_at, deleted_at
`

type CreateProjectParams struct {
	UserID        uuid.UUID      `json:"user_id"`
	Name          string         `json:"name"`
	RepoUrl       string         `json:"repo_url"`
	Branch        string         `json:"branch"`
	Subdomain     string         `json:"subdomain"`
	DeployMode    string         `json:"deploy_mode"`
	MainService   *string        `json:"main_service"`
	AppPort       int32          `json:"app_port"`
	WebhookSecret string         `json:"webhook_secret"`
	MemoryLimitMb int32          `json:"memory_limit_mb"`
	CpuLimit      pgtype.Numeric `json:"cpu_limit"`
}

func (q *Queries) CreateProject(ctx context.Context, arg CreateProjectParams) (Project, error) {
	row := q.db.QueryRow(ctx, createProject,
		arg.UserID,
		arg.Name,
		arg.RepoUrl,
		arg.Branch,
		arg.Subdomain,
		arg.DeployMode,
		arg.MainService,
		arg.AppPort,
		arg.WebhookSecret,
		arg.MemoryLimitMb,
		arg.CpuLimit,
	)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.RepoUrl,
		&i.Branch,
		&i.Subdomain,
		&i.DeployMode,
		&i.MainService,
		&i.AppPort,
		&i.WebhookSecret,
		&i.AllocatedPort,
		&i.MemoryLimitMb,
		&i.CpuLimit,
		&i.Status,
		&i.ActiveDeploymentID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getProjectByID = `-- name: GetProjectByID :one
SELECT id, user_id, name, repo_url, branch, subdomain, deploy_mode, main_service,
       app_port, webhook_secret, allocated_port, memory_limit_mb, cpu_limit,
       status, active_deployment_id, created_at, updated_at, deleted_at
FROM projects
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetProjectByID(ctx context.Context, id uuid.UUID) (Project, error) {
	row := q.db.QueryRow(ctx, getProjectByID, id)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.RepoUrl,
		&i.Branch,
		&i.Subdomain,
		&i.DeployMode,
		&i.MainService,
		&i.AppPort,
		&i.WebhookSecret,
		&i.AllocatedPort,
		&i.MemoryLimitMb,
		&i.CpuLimit,
		&i.Status,
		&i.ActiveDeploymentID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getProjectByName = `-- name: GetProjectByName :one
SELECT id, user_id, name, repo_url, branch, subdomain, deploy_mode, main_service,
       app_port, webhook_secret, allocated_port, memory_limit_mb, cpu_limit,
       status, active_deployment_id, created_at, updated_at, deleted_at
FROM projects
WHERE name = $1 AND deleted_at IS NULL
`

func (q *Queries) GetProjectByName(ctx context.Context, name string) (Project, error) {
	row := q.db.QueryRow(ctx, getProjectByName, name)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.RepoUrl,
		&i.Branch,
		&i.Subdomain,
		&i.DeployMode,
		&i.MainService,
		&i.AppPort,
		&i.WebhookSecret,
		&i.AllocatedPort,
		&i.MemoryLimitMb,
		&i.CpuLimit,
		&i.Status,
		&i.ActiveDeploymentID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getTotalResourcesByUser = `-- name: GetTotalResourcesByUser :one
SELECT
    COALESCE(SUM(memory_limit_mb), 0)::INT      AS total_memory_mb,
    COALESCE(SUM(cpu_limit), 0.0)::NUMERIC(6,2) AS total_cpu
FROM projects
WHERE user_id = $1
  AND deleted_at IS NULL
`

type GetTotalResourcesByUserRow struct {
	TotalMemoryMb int32          `json:"total_memory_mb"`
	TotalCpu      pgtype.Numeric `json:"total_cpu"`
}

func (q *Queries) GetTotalResourcesByUser(ctx context.Context, userID uuid.UUID) (GetTotalResourcesByUserRow, error) {
	row := q.db.QueryRow(ctx, getTotalResourcesByUser, userID)
	var i GetTotalResourcesByUserRow
	err := row.Scan(&i.TotalMemoryMb, &i.TotalCpu)
	return i, err
}

const getTotalResourcesByUserExcludingProject = `-- name: GetTotalResourcesByUserExcludingProject :one
SELECT
    COALESCE(SUM(memory_limit_mb), 0)::INT      AS total_memory_mb,
    COALESCE(SUM(cpu_limit), 0.0)::NUMERIC(6,2) AS total_cpu
FROM projects
WHERE user_id = $1
  AND id <> $2
  AND deleted_at IS NULL
`

type GetTotalResourcesByUserExcludingProjectParams struct {
	UserID uuid.UUID `json:"user_id"`
	ID     uuid.UUID `json:"id"`
}

type GetTotalResourcesByUserExcludingProjectRow struct {
	TotalMemoryMb int32          `json:"total_memory_mb"`
	TotalCpu      pgtype.Numeric `json:"total_cpu"`
}

func (q *Queries) GetTotalResourcesByUserExcludingProject(ctx context.Context, arg GetTotalResourcesByUserExcludingProjectParams) (GetTotalResourcesByUserExcludingProjectRow, error) {
	row := q.db.QueryRow(ctx, getTotalResourcesByUserExcludingProject, arg.UserID, arg.ID)
	var i GetTotalResourcesByUserExcludingProjectRow
	err := row.Scan(&i.TotalMemoryMb, &i.TotalCpu)
	return i, err
}

const listProjectsByUser = `-- name: ListProjectsByUser :many
SELECT id, user_id, name, repo_url, branch, subdomain, deploy_mode, main_service,
       app_port, webhook_secret, allocated_port, memory_limit_mb, cpu_limit,
       status, active_deployment_id, created_at, updated_at, deleted_at
FROM projects
WHERE user_id = $1 AND deleted_at IS NULL
ORDER BY created_at DESC
`

func (q *Queries) ListProjectsByUser(ctx context.Context, userID uuid.UUID) ([]Project, error) {
	rows, err := q.db.Query(ctx, listProjectsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Project
	for rows.Next() {
		var i Project
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.RepoUrl,
			&i.Branch,
			&i.Subdomain,
			&i.DeployMode,
			&i.MainService,
			&i.AppPort,
			&i.WebhookSecret,
			&i.AllocatedPort,
			&i.MemoryLimitMb,
			&i.CpuLimit,
			&i.Status,
			&i.ActiveDeploymentID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const resetBuildingProjects = `-- name: ResetBuildingProjects :exec
UPDATE projects
SET status     = 'pending',
    updated_at = NOW()
WHERE status = 'building'
  AND deleted_at IS NULL
`

func (q *Queries) ResetBuildingProjects(ctx context.Context) error {
	_, err := q.db.Exec(ctx, resetBuildingProjects)
	return err
}

const setProjectActiveDeployment = `-- name: SetProjectActiveDeployment :exec
UPDATE projects
SET active_deployment_id = $2,
    status               = $3,
    updated_at           = NOW()
WHERE id = $1
`

type SetProjectActiveDeploymentParams struct {
	ID                 uuid.UUID   `json:"id"`
	ActiveDeploymentID pgtype.UUID `json:"active_deployment_id"`
	Status             string      `json:"status"`
}

func (q *Queries) SetProjectActiveDeployment(ctx context.Context, arg SetProjectActiveDeploymentParams) error {
	_, err := q.db.Exec(ctx, setProjectActiveDeployment, arg.ID, arg.ActiveDeploymentID, arg.Status)
	return err
}

const setProjectAllocatedPort = `-- name: SetProjectAllocatedPort :exec
UPDATE projects
SET allocated_port = $2,
    updated_at     = NOW()
WHERE id = $1
`

type SetProjectAllocatedPortParams struct {
	ID            uuid.UUID `json:"id"`
	AllocatedPort *int32    `json:"allocated_port"`
}

func (q *Queries) SetProjectAllocatedPort(ctx context.Context, arg SetProjectAllocatedPortParams) error {
	_, err := q.db.Exec(ctx, setProjectAllocatedPort, arg.ID, arg.AllocatedPort)
	return err
}

const softDeleteProject = `-- name: SoftDeleteProject :exec
UPDATE projects
SET deleted_at = NOW(),
    updated_at = NOW()
WHERE id = $1
`

func (q *Queries) SoftDeleteProject(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, softDeleteProject, id)
	return err
}

const updateProject = `-- name: UpdateProject :exec
UPDATE projects
SET name            = $2,
    subdomain       = $3,
    branch          = $4,
    memory_limit_mb = $5,
    cpu_limit       = $6,
    updated_at      = NOW()
WHERE id = $1 AND deleted_at IS NULL
`

type UpdateProjectParams struct {
	ID            uuid.UUID      `json:"id"`
	Name          string         `json:"name"`
	Subdomain     string         `json:"subdomain"`
	Branch        string         `json:"branch"`
	MemoryLimitMb int32          `json:"memory_limit_mb"`
	CpuLimit      pgtype.Numeric `json:"cpu_limit"`
}

func (q *Queries) UpdateProject(ctx context.Context, arg UpdateProjectParams) error {
	_, err := q.db.Exec(ctx, updateProject,
		arg.ID,
		arg.Name,
		arg.Subdomain,
		arg.Branch,
		arg.MemoryLimitMb,
		arg.CpuLimit,
	)
	return err
}

const updateProjectStatus = `-- name: UpdateProjectStatus :exec
UPDATE projects
SET status     = $2,
    updated_at = NOW()
WHERE id = $1
`

type UpdateProjectStatusParams struct {
	ID     uuid.UUID `json:"id"`
	Status string    `json:"status"`
}

func (q *Queries) UpdateProjectStatus(ctx context.Context, arg UpdateProjectStatusParams) error {
	_, err := q.db.Exec(ctx, updateProjectStatus, arg.ID, arg.Status)
	return err
}

const updateProjectWebhookSecret = `-- name: UpdateProjectWebhookSecret :one
UPDATE projects
SET webhook_secret = $2,
    updated_at     = NOW()
WHERE id = $1
  AND deleted_at IS NULL
RETURNING webhook_secret
`

type UpdateProjectWebhookSecretParams struct {
	ID            uuid.UUID `json:"id"`
	WebhookSecret string    `json:"webhook_secret"`
}

func (q *Queries) UpdateProjectWebhookSecret(ctx context.Context, arg UpdateProjectWebhookSecretParams) (string, error) {
	row := q.db.QueryRow(ctx, updateProjectWebhookSecret, arg.ID, arg.WebhookSecret)
	var webhook_secret string
	err := row.Scan(&webhook_secret)
	return webhook_secret, err
}
