// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (email, github_id, github_username, avatar_url, role)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, email, github_id, github_username, avatar_url, role, created_at, last_login_at
`

type CreateUserParams struct {
	Email          string  `json:"email"`
	GithubID       *string `json:"github_id"`
	GithubUsername *string `json:"github_username"`
	AvatarUrl      *string `json:"avatar_url"`
	Role           string  `json:"role"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Email,
		arg.GithubID,
		arg.GithubUsername,
		arg.AvatarUrl,
		arg.Role,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.GithubID,
		&i.GithubUsername,
		&i.AvatarUrl,
		&i.Role,
		&i.CreatedAt,
		&i.LastLoginAt,
	)
	return i, err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users
WHERE id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteUser, id)
	return err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, github_id, github_username, avatar_url, role, created_at, last_login_at
FROM users
WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.GithubID,
		&i.GithubUsername,
		&i.AvatarUrl,
		&i.Role,
		&i.CreatedAt,
		&i.LastLoginAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, github_id, github_username, avatar_url, role, created_at, last_login_at
FROM users
WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.GithubID,
		&i.GithubUsername,
		&i.AvatarUrl,
		&i.Role,
		&i.CreatedAt,
		&i.LastLoginAt,
	)
	return i, err
}

const listUsers = `-- name: ListUsers :many
SELECT id, email, github_id, github_username, avatar_url, role, created_at, last_login_at
FROM users
ORDER BY created_at DESC
`

func (q *Queries) ListUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.Query(ctx, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.GithubID,
			&i.GithubUsername,
			&i.AvatarUrl,
			&i.Role,
			&i.CreatedAt,
			&i.LastLoginAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateLastLogin = `-- name: UpdateLastLogin :exec
UPDATE users
SET last_login_at = NOW()
WHERE id = $1
`

func (q *Queries) UpdateLastLogin(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, updateLastLogin, id)
	return err
}

const updateUserGithubProfile = `-- name: UpdateUserGithubProfile :one
UPDATE users
SET github_id = $2,
    github_username = $3,
    avatar_url = $4,
    last_login_at = NOW()
WHERE id = $1
RETURNING id, email, github_id, github_username, avatar_url, role, created_at, last_login_at
`

type UpdateUserGithubProfileParams struct {
	ID             uuid.UUID `json:"id"`
	GithubID       *string   `json:"github_id"`
	GithubUsername *string   `json:"github_username"`
	AvatarUrl      *string   `json:"avatar_url"`
}

func (q *Queries) UpdateUserGithubProfile(ctx context.Context, arg UpdateUserGithubProfileParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserGithubProfile,
		arg.ID,
		arg.GithubID,
		arg.GithubUsername,
		arg.AvatarUrl,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.GithubID,
		&i.GithubUsername,
		&i.AvatarUrl,
		&i.Role,
		&i.CreatedAt,
		&i.LastLoginAt,
	)
	return i, err
}
