// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: webhook_deliveries.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createWebhookDelivery = `-- name: CreateWebhookDelivery :one
INSERT INTO webhook_deliveries (
    project_id,
    github_delivery_id,
    signature_valid,
    event_type,
    branch,
    processed,
    deployment_id
) VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, project_id, github_delivery_id, signature_valid, event_type,
          branch, processed, deployment_id, received_at
`

type CreateWebhookDeliveryParams struct {
	ProjectID        uuid.UUID   `json:"project_id"`
	GithubDeliveryID *string     `json:"github_delivery_id"`
	SignatureValid   bool        `json:"signature_valid"`
	EventType        *string     `json:"event_type"`
	Branch           *string     `json:"branch"`
	Processed        bool        `json:"processed"`
	DeploymentID     pgtype.UUID `json:"deployment_id"`
}

func (q *Queries) CreateWebhookDelivery(ctx context.Context, arg CreateWebhookDeliveryParams) (WebhookDelivery, error) {
	row := q.db.QueryRow(ctx, createWebhookDelivery,
		arg.ProjectID,
		arg.GithubDeliveryID,
		arg.SignatureValid,
		arg.EventType,
		arg.Branch,
		arg.Processed,
		arg.DeploymentID,
	)
	var i WebhookDelivery
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.GithubDeliveryID,
		&i.SignatureValid,
		&i.EventType,
		&i.Branch,
		&i.Processed,
		&i.DeploymentID,
		&i.ReceivedAt,
	)
	return i, err
}

const markWebhookDeliveryProcessed = `-- name: MarkWebhookDeliveryProcessed :exec
UPDATE webhook_deliveries
SET processed     = TRUE,
    deployment_id = $2
WHERE id = $1
`

type MarkWebhookDeliveryProcessedParams struct {
	ID           uuid.UUID   `json:"id"`
	DeploymentID pgtype.UUID `json:"deployment_id"`
}

func (q *Queries) MarkWebhookDeliveryProcessed(ctx context.Context, arg MarkWebhookDeliveryProcessedParams) error {
	_, err := q.db.Exec(ctx, markWebhookDeliveryProcessed, arg.ID, arg.DeploymentID)
	return err
}
